// WARNING: Generated file, do not modify
export const buffs = {
  core_hpSheerForce: {
    sheet: 'Banyue',
    name: 'core_hpSheerForce',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'sheerForce',
      sheet: 'Banyue',
      name: 'core_hpSheerForce',
    },
    team: false,
  },
  core_sheerForce: {
    sheet: 'Banyue',
    name: 'core_sheerForce',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheerForce',
      sheet: 'Banyue',
      name: 'core_sheerForce',
    },
    team: false,
  },
  core_fire_dmg_: {
    sheet: 'Banyue',
    name: 'core_fire_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'core_fire_dmg_',
    },
    team: false,
  },
  core_crit_dmg_: {
    sheet: 'Banyue',
    name: 'core_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Banyue',
      name: 'core_crit_dmg_',
    },
    team: false,
  },
  ability_fire_dmg_: {
    sheet: 'Banyue',
    name: 'ability_fire_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'ability_fire_dmg_',
    },
    team: false,
  },
  m1_fire_resRed_: {
    sheet: 'Banyue',
    name: 'm1_fire_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'm1_fire_resRed_',
    },
    team: false,
  },
  m1_basic_sheer_dmg_: {
    sheet: 'Banyue',
    name: 'm1_basic_sheer_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'Banyue',
      damageType1: 'basic',
      name: 'm1_basic_sheer_dmg_',
    },
    team: false,
  },
  m1_exSpecial_sheer_dmg_: {
    sheet: 'Banyue',
    name: 'm1_exSpecial_sheer_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'Banyue',
      damageType1: 'exSpecial',
      name: 'm1_exSpecial_sheer_dmg_',
    },
    team: false,
  },
  m2_crit_dmg_: {
    sheet: 'Banyue',
    name: 'm2_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Banyue',
      name: 'm2_crit_dmg_',
    },
    team: false,
  },
  m2_fire_dmg_: {
    sheet: 'Banyue',
    name: 'm2_fire_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'm2_fire_dmg_',
    },
    team: false,
  },
  m4_exSpecial_dmg_: {
    sheet: 'Banyue',
    name: 'm4_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Banyue',
      damageType1: 'exSpecial',
      name: 'm4_exSpecial_dmg_',
    },
    team: false,
  },
  m4_basic_dmg_: {
    sheet: 'Banyue',
    name: 'm4_basic_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Banyue',
      damageType1: 'basic',
      name: 'm4_basic_dmg_',
    },
    team: false,
  },
} as const
