// WARNING: Generated file, do not modify
export const buffs = {
  core_crit_dmg_: {
    sheet: 'JuFufu',
    name: 'core_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'JuFufu',
      name: 'core_crit_dmg_',
    },
    team: true,
  },
  core_chain_dmg_: {
    sheet: 'JuFufu',
    name: 'core_chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'JuFufu',
      damageType1: 'chain',
      name: 'core_chain_dmg_',
    },
    team: true,
  },
  core_ult_dmg_: {
    sheet: 'JuFufu',
    name: 'core_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'JuFufu',
      damageType1: 'ult',
      name: 'core_ult_dmg_',
    },
    team: true,
  },
  core_impact: {
    sheet: 'JuFufu',
    name: 'core_impact',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact',
      sheet: 'JuFufu',
      name: 'core_impact',
    },
    team: false,
  },
  m1_crit_: {
    sheet: 'JuFufu',
    name: 'm1_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'JuFufu',
      name: 'm1_crit_',
    },
    team: false,
  },
  m1_stun_: {
    sheet: 'JuFufu',
    name: 'm1_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'JuFufu',
      name: 'm1_stun_',
    },
    team: true,
  },
  m2_crit_dmg_: {
    sheet: 'JuFufu',
    name: 'm2_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'JuFufu',
      name: 'm2_crit_dmg_',
    },
    team: true,
  },
  m4_crit_dmg_: {
    sheet: 'JuFufu',
    name: 'm4_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'JuFufu',
      name: 'm4_crit_dmg_',
    },
    team: false,
  },
  m6_chain_dmg_: {
    sheet: 'JuFufu',
    name: 'm6_chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'JuFufu',
      damageType1: 'chain',
      name: 'm6_chain_dmg_',
    },
    team: false,
  },
} as const
