// WARNING: Generated file, do not modify
export const buffs = {
  core_critDmg: {
    sheet: 'StarlightBilly',
    name: 'core_critDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'StarlightBilly',
      name: 'core_critDmg',
    },
    team: false,
  },
  core_hpSheerForce: {
    sheet: 'StarlightBilly',
    name: 'core_hpSheerForce',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'sheerForce',
      sheet: 'StarlightBilly',
      name: 'core_hpSheerForce',
    },
    team: false,
  },
  ability_dmg_: {
    sheet: 'StarlightBilly',
    name: 'ability_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'ability_dmg_',
    },
    team: false,
  },
  m1_physResIgn: {
    sheet: 'StarlightBilly',
    name: 'm1_physResIgn',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'm1_physResIgn',
    },
    team: false,
  },
  m4_critDmg: {
    sheet: 'StarlightBilly',
    name: 'm4_critDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'StarlightBilly',
      name: 'm4_critDmg',
    },
    team: false,
  },
  m2_dmg_: {
    sheet: 'StarlightBilly',
    name: 'm2_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'm2_dmg_',
    },
    team: false,
  },
  m6_sheer_: {
    sheet: 'StarlightBilly',
    name: 'm6_sheer_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'm6_sheer_',
    },
    team: false,
  },
} as const
