// WARNING: Generated file, do not modify
export const buffs = {
  core_atk: {
    sheet: 'Ben',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'atk',
      sheet: 'Ben',
      name: 'core_atk',
    },
    team: false,
  },
  ability_crit_: {
    sheet: 'Ben',
    name: 'ability_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Ben',
      name: 'ability_crit_',
    },
    team: true,
  },
  m1_dmg_red_: {
    sheet: 'Ben',
    name: 'm1_dmg_red_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_red_',
      sheet: 'Ben',
      name: 'm1_dmg_red_',
    },
    team: true,
  },
  m4_dmg_: {
    sheet: 'Ben',
    name: 'm4_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Ben',
      name: 'm4_dmg_',
    },
    team: false,
  },
  m6_basic_dazeInc_: {
    sheet: 'Ben',
    name: 'm6_basic_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Ben',
      damageType1: 'basic',
      name: 'm6_basic_dazeInc_',
    },
    team: false,
  },
  m6_dash_dazeInc_: {
    sheet: 'Ben',
    name: 'm6_dash_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Ben',
      damageType1: 'dash',
      name: 'm6_dash_dazeInc_',
    },
    team: false,
  },
  m6_dodgeCounter_dazeInc_: {
    sheet: 'Ben',
    name: 'm6_dodgeCounter_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Ben',
      damageType1: 'dodgeCounter',
      name: 'm6_dodgeCounter_dazeInc_',
    },
    team: false,
  },
} as const
