// WARNING: Generated file, do not modify
export const buffs = {
  etherVeil_hp_: {
    sheet: 'Yidhari',
    name: 'etherVeil_hp_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'hp_',
      sheet: 'Yidhari',
      name: 'etherVeil_hp_',
    },
    team: true,
  },
  core_hpSheerForce: {
    sheet: 'Yidhari',
    name: 'core_hpSheerForce',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'sheerForce',
      sheet: 'Yidhari',
      name: 'core_hpSheerForce',
    },
    team: false,
  },
  core_common_dmg_: {
    sheet: 'Yidhari',
    name: 'core_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Yidhari',
      name: 'core_common_dmg_',
    },
    team: false,
  },
  ability_crit_dmg_: {
    sheet: 'Yidhari',
    name: 'ability_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Yidhari',
      name: 'ability_crit_dmg_',
    },
    team: false,
  },
  m1_basic_ice_resIgn_: {
    sheet: 'Yidhari',
    name: 'm1_basic_ice_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      name: 'm1_basic_ice_resIgn_',
    },
    team: false,
  },
  m1_exSpecial_ice_resIgn_: {
    sheet: 'Yidhari',
    name: 'm1_exSpecial_ice_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      name: 'm1_exSpecial_ice_resIgn_',
    },
    team: false,
  },
  m2_crit_dmg_: {
    sheet: 'Yidhari',
    name: 'm2_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Yidhari',
      name: 'm2_crit_dmg_',
    },
    team: false,
  },
  m4_hp_: {
    sheet: 'Yidhari',
    name: 'm4_hp_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'hp_',
      sheet: 'Yidhari',
      name: 'm4_hp_',
    },
    team: false,
  },
  m6_sheer_dmg_: {
    sheet: 'Yidhari',
    name: 'm6_sheer_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'Yidhari',
      name: 'm6_sheer_dmg_',
    },
    team: false,
  },
} as const
