// WARNING: Generated file, do not modify
export const buffs = {
  flash_connect_dmg_: {
    sheet: 'Qingyi',
    name: 'flash_connect_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Qingyi',
      name: 'flash_connect_dmg_',
    },
    team: false,
  },
  flash_connect_dazeInc_: {
    sheet: 'Qingyi',
    name: 'flash_connect_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Qingyi',
      name: 'flash_connect_dazeInc_',
    },
    team: false,
  },
  chain_dmg_: {
    sheet: 'Qingyi',
    name: 'chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Qingyi',
      name: 'chain_dmg_',
    },
    team: false,
  },
  core_stun_: {
    sheet: 'Qingyi',
    name: 'core_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Qingyi',
      name: 'core_stun_',
    },
    team: false,
  },
  ability_basic_dazeInc_: {
    sheet: 'Qingyi',
    name: 'ability_basic_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Qingyi',
      damageType1: 'basic',
      name: 'ability_basic_dazeInc_',
    },
    team: false,
  },
  ability_atk: {
    sheet: 'Qingyi',
    name: 'ability_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Qingyi',
      name: 'ability_atk',
    },
    team: false,
  },
  m1_defRed_: {
    sheet: 'Qingyi',
    name: 'm1_defRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'defRed_',
      sheet: 'Qingyi',
      name: 'm1_defRed_',
    },
    team: false,
  },
  m1_crit_: {
    sheet: 'Qingyi',
    name: 'm1_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Qingyi',
      name: 'm1_crit_',
    },
    team: false,
  },
  m2_dazeInc_: {
    sheet: 'Qingyi',
    name: 'm2_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Qingyi',
      name: 'm2_dazeInc_',
    },
    team: false,
  },
  m6_resRed_: {
    sheet: 'Qingyi',
    name: 'm6_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Qingyi',
      name: 'm6_resRed_',
    },
    team: false,
  },
  m6_crit_dmg_: {
    sheet: 'Qingyi',
    name: 'm6_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Qingyi',
      name: 'm6_crit_dmg_',
    },
    team: false,
  },
} as const
