// WARNING: Generated file, do not modify
export const buffs = {
  stance_switch_impact_: {
    sheet: 'Caesar',
    name: 'stance_switch_impact_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact_',
      sheet: 'Caesar',
      name: 'stance_switch_impact_',
    },
    team: false,
  },
  ult_dazeInc_: {
    sheet: 'Caesar',
    name: 'ult_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Caesar',
      damageType1: 'ult',
      name: 'ult_dazeInc_',
    },
    team: false,
  },
  core_atk: {
    sheet: 'Caesar',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Caesar',
      name: 'core_atk',
    },
    team: true,
  },
  ability_dmgInc_: {
    sheet: 'Caesar',
    name: 'ability_dmgInc_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'dmgInc_',
      sheet: 'Caesar',
      name: 'ability_dmgInc_',
    },
    team: true,
  },
  m1_resRed_: {
    sheet: 'Caesar',
    name: 'm1_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Caesar',
      name: 'm1_resRed_',
    },
    team: true,
  },
  m2_enerRegen_: {
    sheet: 'Caesar',
    name: 'm2_enerRegen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'enerRegen_',
      sheet: 'Caesar',
      name: 'm2_enerRegen_',
    },
    team: false,
  },
  m6_exSpecial_assistFollowup_crit_: {
    sheet: 'Caesar',
    name: 'm6_exSpecial_assistFollowup_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Caesar',
      name: 'm6_exSpecial_assistFollowup_crit_',
    },
    team: false,
  },
  m6_dmg_: {
    sheet: 'Caesar',
    name: 'm6_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Caesar',
      name: 'm6_dmg_',
    },
    team: false,
  },
  m6_crit_: {
    sheet: 'Caesar',
    name: 'm6_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Caesar',
      name: 'm6_crit_',
    },
    team: false,
  },
  m6_crit_dmg_: {
    sheet: 'Caesar',
    name: 'm6_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Caesar',
      name: 'm6_crit_dmg_',
    },
    team: false,
  },
} as const
