// WARNING: Generated file, do not modify
export const buffs = {
  core_common_dmg_: {
    sheet: 'Velina',
    name: 'core_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Velina',
      name: 'core_common_dmg_',
    },
    team: false,
  },
  core_anomMas: {
    sheet: 'Velina',
    name: 'core_anomMas',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomMas',
      sheet: 'Velina',
      name: 'core_anomMas',
    },
    team: false,
  },
  core_windbite_vortex_anom_mv_mult_: {
    sheet: 'Velina',
    name: 'core_windbite_vortex_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Velina',
      damageType1: 'vortex',
      name: 'core_windbite_vortex_anom_mv_mult_',
    },
    team: false,
  },
  core_condensedCyclone_abloom_: {
    sheet: 'Velina',
    name: 'core_condensedCyclone_abloom_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'core_condensedCyclone_abloom_',
    },
    team: false,
  },
  core_sweepingCyclone_abloom_: {
    sheet: 'Velina',
    name: 'core_sweepingCyclone_abloom_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'core_sweepingCyclone_abloom_',
    },
    team: false,
  },
  core_wind_anomBuildupRes_: {
    sheet: 'Velina',
    name: 'core_wind_anomBuildupRes_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'anomBuildupRes_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'core_wind_anomBuildupRes_',
    },
    team: false,
  },
  core_chromatic_anomBuildupRes_: {
    sheet: 'Velina',
    name: 'core_chromatic_anomBuildupRes_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'anomBuildupRes_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'core_chromatic_anomBuildupRes_',
    },
    team: false,
  },
  ability_wind_dmg_: {
    sheet: 'Velina',
    name: 'ability_wind_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Velina',
      damageType1: 'windswept',
      name: 'ability_wind_dmg_',
    },
    team: false,
  },
  ability_vortex_dmg_: {
    sheet: 'Velina',
    name: 'ability_vortex_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Velina',
      damageType1: 'vortex',
      name: 'ability_vortex_dmg_',
    },
    team: false,
  },
  ability_ult_abloom_anom_mv_mult_: {
    sheet: 'Velina',
    name: 'ability_ult_abloom_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'ability_ult_abloom_anom_mv_mult_',
    },
    team: false,
  },
  ability_anomBuildupRes_: {
    sheet: 'Velina',
    name: 'ability_anomBuildupRes_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'anomBuildupRes_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'ability_anomBuildupRes_',
    },
    team: false,
  },
  ability_dazeInc_: {
    sheet: 'Velina',
    name: 'ability_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Velina',
      name: 'ability_dazeInc_',
    },
    team: false,
  },
  ability_anomBuildup_: {
    sheet: 'Velina',
    name: 'ability_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'ability_anomBuildup_',
    },
    team: false,
  },
  m1_wind_resIgn_: {
    sheet: 'Velina',
    name: 'm1_wind_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'm1_wind_resIgn_',
    },
    team: false,
  },
  m1_all_resIgn_: {
    sheet: 'Velina',
    name: 'm1_all_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Velina',
      name: 'm1_all_resIgn_',
    },
    team: false,
  },
  m2_wind_dmg_: {
    sheet: 'Velina',
    name: 'm2_wind_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Velina',
      damageType1: 'windswept',
      name: 'm2_wind_dmg_',
    },
    team: false,
  },
  m2_vortex_dmg_: {
    sheet: 'Velina',
    name: 'm2_vortex_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Velina',
      damageType1: 'vortex',
      name: 'm2_vortex_dmg_',
    },
    team: false,
  },
  m4_atk_: {
    sheet: 'Velina',
    name: 'm4_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'Velina',
      name: 'm4_atk_',
    },
    team: false,
  },
  m6_wind_anomBuildup_: {
    sheet: 'Velina',
    name: 'm6_wind_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'm6_wind_anomBuildup_',
    },
    team: false,
  },
} as const
