// WARNING: Generated file, do not modify
export const buffs = {
  core_impact_: {
    sheet: 'Lighter',
    name: 'core_impact_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact_',
      sheet: 'Lighter',
      name: 'core_impact_',
    },
    team: false,
  },
  core_ice_resRed_: {
    sheet: 'Lighter',
    name: 'core_ice_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Lighter',
      attribute: 'ice',
      name: 'core_ice_resRed_',
    },
    team: false,
  },
  core_fire_resRed_: {
    sheet: 'Lighter',
    name: 'core_fire_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'core_fire_resRed_',
    },
    team: false,
  },
  ability_ice_dmg_: {
    sheet: 'Lighter',
    name: 'ability_ice_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Lighter',
      attribute: 'ice',
      name: 'ability_ice_dmg_',
    },
    team: true,
  },
  ability_fire_dmg_: {
    sheet: 'Lighter',
    name: 'ability_fire_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'ability_fire_dmg_',
    },
    team: true,
  },
  m1_ice_resRed_: {
    sheet: 'Lighter',
    name: 'm1_ice_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Lighter',
      attribute: 'ice',
      name: 'm1_ice_resRed_',
    },
    team: false,
  },
  m1_fire_resRed_: {
    sheet: 'Lighter',
    name: 'm1_fire_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'm1_fire_resRed_',
    },
    team: false,
  },
  m1_finishing_move_dmg_: {
    sheet: 'Lighter',
    name: 'm1_finishing_move_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Lighter',
      name: 'm1_finishing_move_dmg_',
    },
    team: false,
  },
  m2_stun_: {
    sheet: 'Lighter',
    name: 'm2_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Lighter',
      name: 'm2_stun_',
    },
    team: false,
  },
  m4_enerRegen_: {
    sheet: 'Lighter',
    name: 'm4_enerRegen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'enerRegen_',
      sheet: 'Lighter',
      name: 'm4_enerRegen_',
    },
    team: true,
  },
} as const
