// WARNING: Generated file, do not modify
export const buffs = {
  basic_electric_dmg_: {
    sheet: 'Yanagi',
    name: 'basic_electric_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'basic_electric_dmg_',
    },
    team: false,
  },
  basic_pen_: {
    sheet: 'Yanagi',
    name: 'basic_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Yanagi',
      name: 'basic_pen_',
    },
    team: false,
  },
  polarity_anom_base_: {
    sheet: 'Yanagi',
    name: 'polarity_anom_base_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_base_',
      sheet: 'Yanagi',
      damageType1: 'disorder',
      name: 'polarity_anom_base_',
    },
    team: false,
  },
  polarity_anom_flat_dmg: {
    sheet: 'Yanagi',
    name: 'polarity_anom_flat_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_flat_dmg',
      sheet: 'Yanagi',
      damageType1: 'disorder',
      name: 'polarity_anom_flat_dmg',
    },
    team: false,
  },
  core_addl_disorder_: {
    sheet: 'Yanagi',
    name: 'core_addl_disorder_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'addl_disorder_',
      sheet: 'Yanagi',
      name: 'core_addl_disorder_',
    },
    team: true,
  },
  core_electric_dmg_: {
    sheet: 'Yanagi',
    name: 'core_electric_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'core_electric_dmg_',
    },
    team: false,
  },
  m1_anomProf: {
    sheet: 'Yanagi',
    name: 'm1_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'Yanagi',
      name: 'm1_anomProf',
    },
    team: false,
  },
  m4_pen_: {
    sheet: 'Yanagi',
    name: 'm4_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Yanagi',
      name: 'm4_pen_',
    },
    team: true,
  },
  m6_exSpecial_dmg_: {
    sheet: 'Yanagi',
    name: 'm6_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yanagi',
      damageType1: 'exSpecial',
      name: 'm6_exSpecial_dmg_',
    },
    team: false,
  },
} as const
