// WARNING: Generated file, do not modify
export const buffs = {
  core_anomProf: {
    sheet: 'NangongYu',
    name: 'core_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'NangongYu',
      name: 'core_anomProf',
    },
    team: false,
  },
  core_impact: {
    sheet: 'NangongYu',
    name: 'core_impact',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact',
      sheet: 'NangongYu',
      name: 'core_impact',
    },
    team: false,
  },
  core_anomBuildup_: {
    sheet: 'NangongYu',
    name: 'core_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'core_anomBuildup_',
    },
    team: false,
  },
  core_daze_: {
    sheet: 'NangongYu',
    name: 'core_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'NangongYu',
      name: 'core_daze_',
    },
    team: false,
  },
  core_squad_dmg_: {
    sheet: 'NangongYu',
    name: 'core_squad_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'NangongYu',
      name: 'core_squad_dmg_',
    },
    team: true,
  },
  core_etherVeil_atk: {
    sheet: 'NangongYu',
    name: 'core_etherVeil_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'NangongYu',
      name: 'core_etherVeil_atk',
    },
    team: true,
  },
  m1_resIgn_: {
    sheet: 'NangongYu',
    name: 'm1_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'NangongYu',
      name: 'm1_resIgn_',
    },
    team: false,
  },
  m4_anomProf: {
    sheet: 'NangongYu',
    name: 'm4_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'NangongYu',
      name: 'm4_anomProf',
    },
    team: false,
  },
  m4_basicAnomalyBuildup_: {
    sheet: 'NangongYu',
    name: 'm4_basicAnomalyBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'm4_basicAnomalyBuildup_',
    },
    team: false,
  },
  m6_daze_: {
    sheet: 'NangongYu',
    name: 'm6_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'NangongYu',
      name: 'm6_daze_',
    },
    team: false,
  },
} as const
