// WARNING: Generated file, do not modify
export const buffs = {
  passion_physical_anomBuildup_: {
    sheet: 'Jane',
    name: 'passion_physical_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'passion_physical_anomBuildup_',
    },
    team: false,
  },
  passion_atk: {
    sheet: 'Jane',
    name: 'passion_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Jane',
      name: 'passion_atk',
    },
    team: false,
  },
  core_assault_crit_: {
    sheet: 'Jane',
    name: 'core_assault_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'core_assault_crit_',
    },
    team: true,
  },
  core_assault_crit_dmg_: {
    sheet: 'Jane',
    name: 'core_assault_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_dmg_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'core_assault_crit_dmg_',
    },
    team: true,
  },
  ability_physical_anomBuildup_: {
    sheet: 'Jane',
    name: 'ability_physical_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'ability_physical_anomBuildup_',
    },
    team: false,
  },
  m1_physical_anomBuildup_: {
    sheet: 'Jane',
    name: 'm1_physical_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'm1_physical_anomBuildup_',
    },
    team: false,
  },
  m1_common_dmg_: {
    sheet: 'Jane',
    name: 'm1_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Jane',
      name: 'm1_common_dmg_',
    },
    team: false,
  },
  m2_defIgn_: {
    sheet: 'Jane',
    name: 'm2_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Jane',
      name: 'm2_defIgn_',
    },
    team: false,
  },
  m2_assault_defIgn_: {
    sheet: 'Jane',
    name: 'm2_assault_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'm2_assault_defIgn_',
    },
    team: true,
  },
  m2_assault_crit_dmg_: {
    sheet: 'Jane',
    name: 'm2_assault_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_dmg_',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'm2_assault_crit_dmg_',
    },
    team: true,
  },
  m4_anomaly_dmg_: {
    sheet: 'Jane',
    name: 'm4_anomaly_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Jane',
      damageType1: 'anomaly',
      name: 'm4_anomaly_dmg_',
    },
    team: false,
  },
  m6_crit_: {
    sheet: 'Jane',
    name: 'm6_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Jane',
      name: 'm6_crit_',
    },
    team: false,
  },
  m6_crit_dmg_: {
    sheet: 'Jane',
    name: 'm6_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Jane',
      name: 'm6_crit_dmg_',
    },
    team: false,
  },
} as const
