// WARNING: Generated file, do not modify
export const buffs = {
  special_teamDmg_: {
    sheet: 'Remielle',
    name: 'special_teamDmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Remielle',
      name: 'special_teamDmg_',
    },
    team: true,
  },
  ability_atkBuff: {
    sheet: 'Remielle',
    name: 'ability_atkBuff',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Remielle',
      name: 'ability_atkBuff',
    },
    team: true,
  },
  ability_dazeInc_: {
    sheet: 'Remielle',
    name: 'ability_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Remielle',
      name: 'ability_dazeInc_',
    },
    team: false,
  },
  core_refringeCoeff_: {
    sheet: 'Remielle',
    name: 'core_refringeCoeff_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'refringeCoeff_',
      sheet: 'Remielle',
      name: 'core_refringeCoeff_',
    },
    team: false,
  },
  core_luminize_anom_mv_mult_: {
    sheet: 'Remielle',
    name: 'core_luminize_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Remielle',
      name: 'core_luminize_anom_mv_mult_',
    },
    team: false,
  },
  m1_allResIgn_: {
    sheet: 'Remielle',
    name: 'm1_allResIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'luminize',
      name: 'm1_allResIgn_',
    },
    team: false,
  },
  m1_teamAnomDmg_: {
    sheet: 'Remielle',
    name: 'm1_teamAnomDmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Remielle',
      damageType1: 'anomaly',
      name: 'm1_teamAnomDmg_',
    },
    team: true,
  },
  m2_teamAnomDefIgn_: {
    sheet: 'Remielle',
    name: 'm2_teamAnomDefIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Remielle',
      damageType1: 'anomaly',
      name: 'm2_teamAnomDefIgn_',
    },
    team: true,
  },
  m4_luminizeDmg_: {
    sheet: 'Remielle',
    name: 'm4_luminizeDmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'luminize',
      name: 'm4_luminizeDmg_',
    },
    team: false,
  },
} as const
