// WARNING: Generated file, do not modify
export const buffs = {
  core_prophecy_dmg: {
    sheet: 'Vivian',
    name: 'core_prophecy_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Vivian',
      attribute: 'ether',
      name: 'core_prophecy_dmg',
    },
    team: false,
  },
  core_ether_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_ether_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'ether',
      damageType1: 'abloom',
      name: 'core_ether_anom_mv_mult_',
    },
    team: false,
  },
  core_electric_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_electric_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'electric',
      damageType1: 'abloom',
      name: 'core_electric_anom_mv_mult_',
    },
    team: false,
  },
  core_fire_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_fire_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'fire',
      damageType1: 'abloom',
      name: 'core_fire_anom_mv_mult_',
    },
    team: false,
  },
  core_physical_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_physical_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'physical',
      damageType1: 'abloom',
      name: 'core_physical_anom_mv_mult_',
    },
    team: false,
  },
  core_ice_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_ice_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'ice',
      damageType1: 'abloom',
      name: 'core_ice_anom_mv_mult_',
    },
    team: false,
  },
  core_wind_anom_mv_mult_: {
    sheet: 'Vivian',
    name: 'core_wind_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Vivian',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'core_wind_anom_mv_mult_',
    },
    team: false,
  },
  ability_corruption_dmg_: {
    sheet: 'Vivian',
    name: 'ability_corruption_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Vivian',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'ability_corruption_dmg_',
    },
    team: true,
  },
  ability_corruption_disorder_dmg_: {
    sheet: 'Vivian',
    name: 'ability_corruption_disorder_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Vivian',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'ability_corruption_disorder_dmg_',
    },
    team: true,
  },
  m1_anomaly_dmg_: {
    sheet: 'Vivian',
    name: 'm1_anomaly_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Vivian',
      damageType1: 'anomaly',
      name: 'm1_anomaly_dmg_',
    },
    team: true,
  },
  m1_disorder_dmg_: {
    sheet: 'Vivian',
    name: 'm1_disorder_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'buff_',
      sheet: 'Vivian',
      damageType1: 'disorder',
      name: 'm1_disorder_dmg_',
    },
    team: true,
  },
  m2_resIgn_: {
    sheet: 'Vivian',
    name: 'm2_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Vivian',
      damageType1: 'anomaly',
      name: 'm2_resIgn_',
    },
    team: true,
  },
  m4_suspension_crit_: {
    sheet: 'Vivian',
    name: 'm4_suspension_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Vivian',
      name: 'm4_suspension_crit_',
    },
    team: false,
  },
  m4_featherbloom_crit_: {
    sheet: 'Vivian',
    name: 'm4_featherbloom_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Vivian',
      name: 'm4_featherbloom_crit_',
    },
    team: false,
  },
  m4_atk_: {
    sheet: 'Vivian',
    name: 'm4_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'Vivian',
      name: 'm4_atk_',
    },
    team: false,
  },
  m6_ether_dmg_: {
    sheet: 'Vivian',
    name: 'm6_ether_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Vivian',
      attribute: 'ether',
      name: 'm6_ether_dmg_',
    },
    team: false,
  },
} as const
