// WARNING: Generated file, do not modify
export const buffs = {
  catsgaze_dmg_fire: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_fire',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_fire',
    },
    team: false,
  },
  catsgaze_dmg_electric: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_electric',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_electric',
    },
    team: false,
  },
  catsgaze_dmg_ice: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_ice',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_ice',
    },
    team: false,
  },
  catsgaze_dmg_physical: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_physical',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_physical',
    },
    team: false,
  },
  catsgaze_dmg_ether: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_ether',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_ether',
    },
    team: false,
  },
  catsgaze_dmg_wind: {
    sheet: 'Sunna',
    name: 'catsgaze_dmg_wind',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'catsgaze_dmg_wind',
    },
    team: false,
  },
  m6_catsgaze_dmg: {
    sheet: 'Sunna',
    name: 'm6_catsgaze_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Sunna',
      damageType1: 'elemental',
      name: 'm6_catsgaze_dmg',
    },
    team: false,
  },
  core_atk: {
    sheet: 'Sunna',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Sunna',
      name: 'core_atk',
    },
    team: true,
  },
  reprise_atk: {
    sheet: 'Sunna',
    name: 'reprise_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Sunna',
      name: 'reprise_atk',
    },
    team: true,
  },
  ability_stun_: {
    sheet: 'Sunna',
    name: 'ability_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Sunna',
      name: 'ability_stun_',
    },
    team: true,
  },
  m1_defRed_: {
    sheet: 'Sunna',
    name: 'm1_defRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'defRed_',
      sheet: 'Sunna',
      name: 'm1_defRed_',
    },
    team: true,
  },
  m2_etherVeil_atk: {
    sheet: 'Sunna',
    name: 'm2_etherVeil_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'Sunna',
      name: 'm2_etherVeil_atk',
    },
    team: true,
  },
  m4_dmg_: {
    sheet: 'Sunna',
    name: 'm4_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Sunna',
      name: 'm4_dmg_',
    },
    team: true,
  },
  m6_crit_: {
    sheet: 'Sunna',
    name: 'm6_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Sunna',
      name: 'm6_crit_',
    },
    team: false,
  },
  m6_crit_dmg_: {
    sheet: 'Sunna',
    name: 'm6_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Sunna',
      name: 'm6_crit_dmg_',
    },
    team: false,
  },
  m6_catsgaze_dmg_: {
    sheet: 'Sunna',
    name: 'm6_catsgaze_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Sunna',
      name: 'm6_catsgaze_dmg_',
    },
    team: false,
  },
} as const
