// WARNING: Generated file, do not modify
export const buffs = {
  core_regen_atk: {
    sheet: 'Roxy',
    name: 'core_regen_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Roxy',
      name: 'core_regen_atk',
    },
    team: false,
  },
  core_regen_impact: {
    sheet: 'Roxy',
    name: 'core_regen_impact',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact',
      sheet: 'Roxy',
      name: 'core_regen_impact',
    },
    team: false,
  },
  core_team_crit_dmg_: {
    sheet: 'Roxy',
    name: 'core_team_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Roxy',
      name: 'core_team_crit_dmg_',
    },
    team: true,
  },
  core_team_laceration_: {
    sheet: 'Roxy',
    name: 'core_team_laceration_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'laceration_dmg_',
      sheet: 'Roxy',
      name: 'core_team_laceration_',
    },
    team: true,
  },
  ability_self_dmg_: {
    sheet: 'Roxy',
    name: 'ability_self_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Roxy',
      name: 'ability_self_dmg_',
    },
    team: false,
  },
  ability_stun_: {
    sheet: 'Roxy',
    name: 'ability_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Roxy',
      name: 'ability_stun_',
    },
    team: true,
  },
  ability_windswept_dmgInc_: {
    sheet: 'Roxy',
    name: 'ability_windswept_dmgInc_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'dmgInc_',
      sheet: 'Roxy',
      name: 'ability_windswept_dmgInc_',
    },
    team: true,
  },
  ability_ex_anomBuildup_: {
    sheet: 'Roxy',
    name: 'ability_ex_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Roxy',
      name: 'ability_ex_anomBuildup_',
    },
    team: false,
  },
  m1_allResRed_: {
    sheet: 'Roxy',
    name: 'm1_allResRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Roxy',
      name: 'm1_allResRed_',
    },
    team: true,
  },
  m1_crit_dmg_: {
    sheet: 'Roxy',
    name: 'm1_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Roxy',
      name: 'm1_crit_dmg_',
    },
    team: false,
  },
  m2_ex_daze_: {
    sheet: 'Roxy',
    name: 'm2_ex_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Roxy',
      name: 'm2_ex_daze_',
    },
    team: false,
  },
  m2_stun_: {
    sheet: 'Roxy',
    name: 'm2_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Roxy',
      name: 'm2_stun_',
    },
    team: true,
  },
  m4_ult_dmg_: {
    sheet: 'Roxy',
    name: 'm4_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Roxy',
      name: 'm4_ult_dmg_',
    },
    team: false,
  },
  m4_ult_daze_: {
    sheet: 'Roxy',
    name: 'm4_ult_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Roxy',
      name: 'm4_ult_daze_',
    },
    team: false,
  },
  m6_wind_resIgn_: {
    sheet: 'Roxy',
    name: 'm6_wind_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'm6_wind_resIgn_',
    },
    team: false,
  },
  m6_afterecho_daze_: {
    sheet: 'Roxy',
    name: 'm6_afterecho_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Roxy',
      name: 'm6_afterecho_daze_',
    },
    team: false,
  },
  m6_afterecho_mult_display_: {
    sheet: 'Roxy',
    name: 'm6_afterecho_mult_display_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Roxy',
      name: 'm6_afterecho_mult_display_',
    },
    team: false,
  },
} as const
