// WARNING: Generated file, do not modify
export const buffs = {
  m6_dmg: {
    sheet: 'Harumasa',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Harumasa',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
    team: false,
  },
  core_dash_crit_: {
    sheet: 'Harumasa',
    name: 'core_dash_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Harumasa',
      damageType1: 'dash',
      name: 'core_dash_crit_',
    },
    team: false,
  },
  core_chasing_thunder_crit_: {
    sheet: 'Harumasa',
    name: 'core_chasing_thunder_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Harumasa',
      damageType1: 'dash',
      name: 'core_chasing_thunder_crit_',
    },
    team: false,
  },
  core_ult_crit_: {
    sheet: 'Harumasa',
    name: 'core_ult_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Harumasa',
      damageType1: 'ult',
      name: 'core_ult_crit_',
    },
    team: false,
  },
  core_dash_crit_dmg_: {
    sheet: 'Harumasa',
    name: 'core_dash_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Harumasa',
      damageType1: 'dash',
      name: 'core_dash_crit_dmg_',
    },
    team: false,
  },
  core_chasing_thunder_crit_dmg_: {
    sheet: 'Harumasa',
    name: 'core_chasing_thunder_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Harumasa',
      damageType1: 'dash',
      name: 'core_chasing_thunder_crit_dmg_',
    },
    team: false,
  },
  core_ult_crit_dmg_: {
    sheet: 'Harumasa',
    name: 'core_ult_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Harumasa',
      damageType1: 'ult',
      name: 'core_ult_crit_dmg_',
    },
    team: false,
  },
  ability_common_dmg_: {
    sheet: 'Harumasa',
    name: 'ability_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Harumasa',
      name: 'ability_common_dmg_',
    },
    team: false,
  },
  m2_dash_dmg_: {
    sheet: 'Harumasa',
    name: 'm2_dash_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Harumasa',
      damageType1: 'dash',
      name: 'm2_dash_dmg_',
    },
    team: false,
  },
  m6_electric_resIgn_: {
    sheet: 'Harumasa',
    name: 'm6_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'm6_electric_resIgn_',
    },
    team: false,
  },
  potential_atk_: {
    sheet: 'Harumasa',
    name: 'potential_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'Harumasa',
      name: 'potential_atk_',
    },
    team: false,
  },
  potential_dash_electric_resIgn_: {
    sheet: 'Harumasa',
    name: 'potential_dash_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      name: 'potential_dash_electric_resIgn_',
    },
    team: false,
  },
  potential_chasing_thunder_electric_resIgn_: {
    sheet: 'Harumasa',
    name: 'potential_chasing_thunder_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      name: 'potential_chasing_thunder_electric_resIgn_',
    },
    team: false,
  },
} as const
