// WARNING: Generated file, do not modify
export const buffs = {
  core_atk: {
    sheet: 'Seed',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Seed',
      name: 'core_atk',
    },
    team: false,
  },
  core_crit_dmg_: {
    sheet: 'Seed',
    name: 'core_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Seed',
      name: 'core_crit_dmg_',
    },
    team: false,
  },
  core_vanguard_atk: {
    sheet: 'Seed',
    name: 'core_vanguard_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Seed',
      name: 'core_vanguard_atk',
    },
    team: true,
  },
  core_vanguard_crit_dmg_: {
    sheet: 'Seed',
    name: 'core_vanguard_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Seed',
      name: 'core_vanguard_crit_dmg_',
    },
    team: true,
  },
  core_dmg_: {
    sheet: 'Seed',
    name: 'core_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Seed',
      name: 'core_dmg_',
    },
    team: true,
  },
  ability_basic_dmg_: {
    sheet: 'Seed',
    name: 'ability_basic_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Seed',
      damageType1: 'basic',
      name: 'ability_basic_dmg_',
    },
    team: false,
  },
  ability_basic_electric_resIgn_: {
    sheet: 'Seed',
    name: 'ability_basic_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Seed',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'ability_basic_electric_resIgn_',
    },
    team: false,
  },
  ability_ult_dmg_: {
    sheet: 'Seed',
    name: 'ability_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Seed',
      damageType1: 'ult',
      name: 'ability_ult_dmg_',
    },
    team: false,
  },
  ability_ult_electric_resIgn_: {
    sheet: 'Seed',
    name: 'ability_ult_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Seed',
      attribute: 'electric',
      damageType1: 'ult',
      name: 'ability_ult_electric_resIgn_',
    },
    team: false,
  },
  m1_basic_crit_dmg_: {
    sheet: 'Seed',
    name: 'm1_basic_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Seed',
      damageType1: 'basic',
      name: 'm1_basic_crit_dmg_',
    },
    team: false,
  },
  m2_defIgn_: {
    sheet: 'Seed',
    name: 'm2_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Seed',
      name: 'm2_defIgn_',
    },
    team: false,
  },
  m2_vanguard_defIgn_: {
    sheet: 'Seed',
    name: 'm2_vanguard_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Seed',
      name: 'm2_vanguard_defIgn_',
    },
    team: true,
  },
  m2_basic_dmg_: {
    sheet: 'Seed',
    name: 'm2_basic_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Seed',
      damageType1: 'basic',
      name: 'm2_basic_dmg_',
    },
    team: false,
  },
  m4_ult_dmg_: {
    sheet: 'Seed',
    name: 'm4_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Seed',
      damageType1: 'ult',
      name: 'm4_ult_dmg_',
    },
    team: false,
  },
  m6_crit_dmg_: {
    sheet: 'Seed',
    name: 'm6_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Seed',
      name: 'm6_crit_dmg_',
    },
    team: false,
  },
} as const
