// WARNING: Generated file, do not modify
export const buffs = {
  core_electric_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_electric_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'electric',
      damageType1: 'abloom',
      name: 'core_electric_anom_mv_mult_',
    },
    team: false,
  },
  core_fire_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_fire_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'fire',
      damageType1: 'abloom',
      name: 'core_fire_anom_mv_mult_',
    },
    team: false,
  },
  core_ice_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_ice_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'ice',
      damageType1: 'abloom',
      name: 'core_ice_anom_mv_mult_',
    },
    team: false,
  },
  core_physical_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_physical_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'physical',
      damageType1: 'abloom',
      name: 'core_physical_anom_mv_mult_',
    },
    team: false,
  },
  core_ether_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_ether_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'abloom',
      name: 'core_ether_anom_mv_mult_',
    },
    team: false,
  },
  core_wind_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'core_wind_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'core_wind_anom_mv_mult_',
    },
    team: false,
  },
  m6_electric_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_electric_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'electric',
      damageType1: 'abloom',
      name: 'm6_electric_anom_mv_mult_',
    },
    team: false,
  },
  m6_fire_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_fire_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'fire',
      damageType1: 'abloom',
      name: 'm6_fire_anom_mv_mult_',
    },
    team: false,
  },
  m6_ice_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_ice_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'ice',
      damageType1: 'abloom',
      name: 'm6_ice_anom_mv_mult_',
    },
    team: false,
  },
  m6_physical_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_physical_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'physical',
      damageType1: 'abloom',
      name: 'm6_physical_anom_mv_mult_',
    },
    team: false,
  },
  m6_ether_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_ether_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'abloom',
      name: 'm6_ether_anom_mv_mult_',
    },
    team: false,
  },
  m6_wind_anom_mv_mult_: {
    sheet: 'NangongYu',
    name: 'm6_wind_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'NangongYu',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'm6_wind_anom_mv_mult_',
    },
    team: false,
  },
  m2_polarity_disorder_dmg: {
    sheet: 'NangongYu',
    name: 'm2_polarity_disorder_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_base_',
      sheet: 'NangongYu',
      damageType1: 'disorder',
      name: 'm2_polarity_disorder_dmg',
    },
    team: false,
  },
  core_anomBuildup_: {
    sheet: 'NangongYu',
    name: 'core_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      name: 'core_anomBuildup_',
    },
    team: false,
  },
  core_daze_: {
    sheet: 'NangongYu',
    name: 'core_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'NangongYu',
      name: 'core_daze_',
    },
    team: false,
  },
  core_squad_dmg_: {
    sheet: 'NangongYu',
    name: 'core_squad_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'NangongYu',
      name: 'core_squad_dmg_',
    },
    team: true,
  },
  core_etherVeil_atk: {
    sheet: 'NangongYu',
    name: 'core_etherVeil_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'NangongYu',
      name: 'core_etherVeil_atk',
    },
    team: true,
  },
  core_anomProf: {
    sheet: 'NangongYu',
    name: 'core_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'NangongYu',
      name: 'core_anomProf',
    },
    team: false,
  },
  core_impact: {
    sheet: 'NangongYu',
    name: 'core_impact',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'impact',
      sheet: 'NangongYu',
      name: 'core_impact',
    },
    team: false,
  },
  ability_squad_anomBuildup_: {
    sheet: 'NangongYu',
    name: 'ability_squad_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      name: 'ability_squad_anomBuildup_',
    },
    team: true,
  },
  ability_chain_anomBuildup_: {
    sheet: 'NangongYu',
    name: 'ability_chain_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      damageType1: 'chain',
      name: 'ability_chain_anomBuildup_',
    },
    team: true,
  },
  ability_misstep_stun_: {
    sheet: 'NangongYu',
    name: 'ability_misstep_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'NangongYu',
      name: 'ability_misstep_stun_',
    },
    team: true,
  },
  m1_resRed_: {
    sheet: 'NangongYu',
    name: 'm1_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'NangongYu',
      name: 'm1_resRed_',
    },
    team: true,
  },
  m4_anomProf: {
    sheet: 'NangongYu',
    name: 'm4_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'NangongYu',
      name: 'm4_anomProf',
    },
    team: false,
  },
  m4_basic_anomBuildup_: {
    sheet: 'NangongYu',
    name: 'm4_basic_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'NangongYu',
      damageType1: 'basic',
      name: 'm4_basic_anomBuildup_',
    },
    team: false,
  },
  m6_daze_: {
    sheet: 'NangongYu',
    name: 'm6_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'NangongYu',
      name: 'm6_daze_',
    },
    team: false,
  },
} as const
