// WARNING: Generated file, do not modify
export const buffs = {
  core_critDmg_: {
    sheet: 'Norma',
    name: 'core_critDmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Norma',
      name: 'core_critDmg_',
    },
    team: false,
  },
  core_exSpecial_dazeInc_: {
    sheet: 'Norma',
    name: 'core_exSpecial_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Norma',
      damageType1: 'exSpecial',
      name: 'core_exSpecial_dazeInc_',
    },
    team: false,
  },
  core_special_dazeInc_: {
    sheet: 'Norma',
    name: 'core_special_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Norma',
      damageType1: 'special',
      name: 'core_special_dazeInc_',
    },
    team: false,
  },
  core_ult_dazeInc_: {
    sheet: 'Norma',
    name: 'core_ult_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Norma',
      damageType1: 'ult',
      name: 'core_ult_dazeInc_',
    },
    team: false,
  },
  core_atk: {
    sheet: 'Norma',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Norma',
      name: 'core_atk',
    },
    team: false,
  },
  ability_atk: {
    sheet: 'Norma',
    name: 'ability_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Norma',
      name: 'ability_atk',
    },
    team: false,
  },
  ability_squadDmg_: {
    sheet: 'Norma',
    name: 'ability_squadDmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Norma',
      name: 'ability_squadDmg_',
    },
    team: true,
  },
  m1_allResRed_: {
    sheet: 'Norma',
    name: 'm1_allResRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'Norma',
      name: 'm1_allResRed_',
    },
    team: false,
  },
  m6_daze_: {
    sheet: 'Norma',
    name: 'm6_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Norma',
      name: 'm6_daze_',
    },
    team: false,
  },
  m6_dmg_: {
    sheet: 'Norma',
    name: 'm6_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Norma',
      name: 'm6_dmg_',
    },
    team: false,
  },
} as const
