// WARNING: Generated file, do not modify
export const buffs = {
  trialByColdAbloomDmg: {
    sheet: 'Promeia',
    name: 'trialByColdAbloomDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'trialByColdAbloomDmg',
    },
    team: false,
  },
  m6SpecialAbloomDmg: {
    sheet: 'Promeia',
    name: 'm6SpecialAbloomDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'm6SpecialAbloomDmg',
    },
    team: false,
  },
  chainAbloomDmg: {
    sheet: 'Promeia',
    name: 'chainAbloomDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'chainAbloomDmg',
    },
    team: false,
  },
  ultAbloomDmg: {
    sheet: 'Promeia',
    name: 'ultAbloomDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'ultAbloomDmg',
    },
    team: false,
  },
  core_anomProf: {
    sheet: 'Promeia',
    name: 'core_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'Promeia',
      name: 'core_anomProf',
    },
    team: false,
  },
  core_abloomDmg: {
    sheet: 'Promeia',
    name: 'core_abloomDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'core_abloomDmg',
    },
    team: true,
  },
  ability_iceAnomBuildup_: {
    sheet: 'Promeia',
    name: 'ability_iceAnomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Promeia',
      attribute: 'ice',
      name: 'ability_iceAnomBuildup_',
    },
    team: false,
  },
  ability_presumptionDefIgn: {
    sheet: 'Promeia',
    name: 'ability_presumptionDefIgn',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Promeia',
      damageType1: 'abloom',
      name: 'ability_presumptionDefIgn',
    },
    team: true,
  },
  m2_anomProf: {
    sheet: 'Promeia',
    name: 'm2_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'Promeia',
      name: 'm2_anomProf',
    },
    team: false,
  },
  m6_resIgn_anomaly: {
    sheet: 'Promeia',
    name: 'm6_resIgn_anomaly',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Promeia',
      damageType1: 'anomaly',
      name: 'm6_resIgn_anomaly',
    },
    team: false,
  },
  m6_resIgn_disorder: {
    sheet: 'Promeia',
    name: 'm6_resIgn_disorder',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Promeia',
      damageType1: 'disorder',
      name: 'm6_resIgn_disorder',
    },
    team: false,
  },
} as const
