// WARNING: Generated file, do not modify
export const buffs = {
  m4_disconnect_dmg: {
    sheet: 'Trigger',
    name: 'm4_disconnect_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Trigger',
      damageType1: 'elemental',
      name: 'm4_disconnect_dmg',
    },
    team: false,
  },
  m4_disconnect_daze: {
    sheet: 'Trigger',
    name: 'm4_disconnect_daze',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Trigger',
      damageType1: 'elemental',
      name: 'm4_disconnect_daze',
    },
    team: false,
  },
  core_stun_: {
    sheet: 'Trigger',
    name: 'core_stun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'stun_',
      sheet: 'Trigger',
      name: 'core_stun_',
    },
    team: true,
  },
  core_stun_unstun_: {
    sheet: 'Trigger',
    name: 'core_stun_unstun_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'unstun_',
      sheet: 'Trigger',
      name: 'core_stun_unstun_',
    },
    team: true,
  },
  ability_aftershock_dazeInc_: {
    sheet: 'Trigger',
    name: 'ability_aftershock_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Trigger',
      damageType1: 'aftershock',
      name: 'ability_aftershock_dazeInc_',
    },
    team: false,
  },
  m2_crit_dmg_: {
    sheet: 'Trigger',
    name: 'm2_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Trigger',
      name: 'm2_crit_dmg_',
    },
    team: true,
  },
  m6_armor_break_rounds_dmg: {
    sheet: 'Trigger',
    name: 'm6_armor_break_rounds_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Trigger',
      name: 'm6_armor_break_rounds_dmg',
    },
    team: false,
  },
} as const
