// WARNING: Generated file, do not modify
export const buffs = {
  core_ether_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_ether_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'abloom',
      name: 'core_ether_anom_mv_mult_',
    },
    team: false,
  },
  core_electric_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_electric_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'electric',
      damageType1: 'abloom',
      name: 'core_electric_anom_mv_mult_',
    },
    team: false,
  },
  core_fire_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_fire_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'fire',
      damageType1: 'abloom',
      name: 'core_fire_anom_mv_mult_',
    },
    team: false,
  },
  core_physical_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_physical_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'physical',
      damageType1: 'abloom',
      name: 'core_physical_anom_mv_mult_',
    },
    team: false,
  },
  core_ice_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_ice_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'ice',
      damageType1: 'abloom',
      name: 'core_ice_anom_mv_mult_',
    },
    team: false,
  },
  core_wind_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_wind_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'wind',
      damageType1: 'abloom',
      name: 'core_wind_anom_mv_mult_',
    },
    team: false,
  },
  core_anomProf: {
    sheet: 'Aria',
    name: 'core_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'Aria',
      name: 'core_anomProf',
    },
    team: false,
  },
  m1_ether_anomBuildupResRed_: {
    sheet: 'Aria',
    name: 'm1_ether_anomBuildupResRed_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildupResRed_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      name: 'm1_ether_anomBuildupResRed_',
    },
    team: false,
  },
  m1_abloom: {
    sheet: 'Aria',
    name: 'm1_abloom',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_',
      sheet: 'Aria',
      name: 'm1_abloom',
    },
    team: false,
  },
  m1_abloom_crit_dmg: {
    sheet: 'Aria',
    name: 'm1_abloom_crit_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_dmg_',
      sheet: 'Aria',
      name: 'm1_abloom_crit_dmg',
    },
    team: false,
  },
  m2_defIgn_base: {
    sheet: 'Aria',
    name: 'm2_defIgn_base',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      name: 'm2_defIgn_base',
    },
    team: false,
  },
  m2_defIgn_delusion: {
    sheet: 'Aria',
    name: 'm2_defIgn_delusion',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      name: 'm2_defIgn_delusion',
    },
    team: false,
  },
  m6_perfectPitch_dmg_: {
    sheet: 'Aria',
    name: 'm6_perfectPitch_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Aria',
      damageType1: 'basic',
      name: 'm6_perfectPitch_dmg_',
    },
    team: false,
  },
  m6_ult_dmg_: {
    sheet: 'Aria',
    name: 'm6_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Aria',
      damageType1: 'ult',
      name: 'm6_ult_dmg_',
    },
    team: false,
  },
  ultimate_atk: {
    sheet: 'Aria',
    name: 'ultimate_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Aria',
      name: 'ultimate_atk',
    },
    team: true,
  },
} as const
