// WARNING: Generated file, do not modify
export const buffs = {
  m6_dmg: {
    sheet: 'OrphieMagus',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'OrphieMagus',
      damageType1: 'aftershock',
      name: 'm6_dmg',
    },
    team: false,
  },
  core_crit_: {
    sheet: 'OrphieMagus',
    name: 'core_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'OrphieMagus',
      name: 'core_crit_',
    },
    team: false,
  },
  core_aftershock_dmg_: {
    sheet: 'OrphieMagus',
    name: 'core_aftershock_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'OrphieMagus',
      damageType1: 'aftershock',
      name: 'core_aftershock_dmg_',
    },
    team: false,
  },
  core_atk: {
    sheet: 'OrphieMagus',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'OrphieMagus',
      name: 'core_atk',
    },
    team: true,
  },
  ability_aftershock_defIgn_: {
    sheet: 'OrphieMagus',
    name: 'ability_aftershock_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'OrphieMagus',
      damageType1: 'aftershock',
      name: 'ability_aftershock_defIgn_',
    },
    team: true,
  },
  m1_corrosiveFlash_resIgn_: {
    sheet: 'OrphieMagus',
    name: 'm1_corrosiveFlash_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'OrphieMagus',
      attribute: 'fire',
      name: 'm1_corrosiveFlash_resIgn_',
    },
    team: false,
  },
  m1_crimsonVortex_resIgn_: {
    sheet: 'OrphieMagus',
    name: 'm1_crimsonVortex_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'OrphieMagus',
      attribute: 'fire',
      name: 'm1_crimsonVortex_resIgn_',
    },
    team: false,
  },
  m1_heatCharge_resIgn_: {
    sheet: 'OrphieMagus',
    name: 'm1_heatCharge_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'OrphieMagus',
      attribute: 'fire',
      name: 'm1_heatCharge_resIgn_',
    },
    team: false,
  },
  m1_fieryEruption_resIgn_: {
    sheet: 'OrphieMagus',
    name: 'm1_fieryEruption_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'OrphieMagus',
      attribute: 'fire',
      name: 'm1_fieryEruption_resIgn_',
    },
    team: false,
  },
  m1_common_dmg_: {
    sheet: 'OrphieMagus',
    name: 'm1_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'OrphieMagus',
      name: 'm1_common_dmg_',
    },
    team: true,
  },
  m2_atk_: {
    sheet: 'OrphieMagus',
    name: 'm2_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'OrphieMagus',
      name: 'm2_atk_',
    },
    team: false,
  },
  m4_heatCharge_dmg_: {
    sheet: 'OrphieMagus',
    name: 'm4_heatCharge_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'OrphieMagus',
      name: 'm4_heatCharge_dmg_',
    },
    team: false,
  },
  m4_ultimate_dmg_: {
    sheet: 'OrphieMagus',
    name: 'm4_ultimate_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'OrphieMagus',
      name: 'm4_ultimate_dmg_',
    },
    team: false,
  },
} as const
