// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Remielle',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'standardDmgInst',
    },
  },
  dazeInst: {
    sheet: 'Remielle',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'dazeInst',
    },
  },
  BasicAttackLeap_0_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_0_dmg',
    },
  },
  BasicAttackLeap_0_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_0_daze',
    },
  },
  BasicAttackLeap_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_0_anomBuildup',
    },
  },
  BasicAttackLeap_1_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_1_dmg',
    },
  },
  BasicAttackLeap_1_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_1_daze',
    },
  },
  BasicAttackLeap_1_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_1_anomBuildup',
    },
  },
  BasicAttackLeap_2_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_2_dmg',
    },
  },
  BasicAttackLeap_2_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_2_daze',
    },
  },
  BasicAttackLeap_2_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_2_anomBuildup',
    },
  },
  BasicAttackLeap_3_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_3_dmg',
    },
  },
  BasicAttackLeap_3_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_3_daze',
    },
  },
  BasicAttackLeap_3_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLeap_3_anomBuildup',
    },
  },
  BasicAttackSoloDance_0_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSoloDance_0_dmg',
    },
  },
  BasicAttackSoloDance_0_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSoloDance_0_daze',
    },
  },
  BasicAttackSoloDance_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSoloDance_0_anomBuildup',
    },
  },
  BasicAttackRainbowsEnd_0_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0_dmg',
    },
  },
  BasicAttackRainbowsEnd_0_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0_daze',
    },
  },
  BasicAttackRainbowsEnd_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0_anomBuildup',
    },
  },
  BasicAttackFleetingGrace_0_dmg: {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0_dmg',
    },
  },
  BasicAttackFleetingGrace_0_daze: {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0_daze',
    },
  },
  BasicAttackFleetingGrace_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0_anomBuildup',
    },
  },
  DashAttackKeenLight_0_dmg: {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackKeenLight_0_dmg',
    },
  },
  DashAttackKeenLight_0_daze: {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackKeenLight_0_daze',
    },
  },
  DashAttackKeenLight_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackKeenLight_0_anomBuildup',
    },
  },
  DodgeCounterMirroredShadow_0_dmg: {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0_dmg',
    },
  },
  DodgeCounterMirroredShadow_0_daze: {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0_daze',
    },
  },
  DodgeCounterMirroredShadow_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0_anomBuildup',
    },
  },
  SpecialAttackSliverOfLight_0_dmg: {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0_dmg',
    },
  },
  SpecialAttackSliverOfLight_0_daze: {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0_daze',
    },
  },
  SpecialAttackSliverOfLight_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0_anomBuildup',
    },
  },
  EXSpecialAttackOdeToDawn_0_dmg: {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0_dmg',
    },
  },
  EXSpecialAttackOdeToDawn_0_daze: {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0_daze',
    },
  },
  EXSpecialAttackOdeToDawn_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0_anomBuildup',
    },
  },
  SpecialAttackOdeToDawnRadiantTurn_0_dmg: {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0_dmg',
    },
  },
  SpecialAttackOdeToDawnRadiantTurn_0_daze: {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0_daze',
    },
  },
  SpecialAttackOdeToDawnRadiantTurn_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0_anomBuildup',
    },
  },
  ChainAttackInterwovenDanceSteps_0_dmg: {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0_dmg',
    },
  },
  ChainAttackInterwovenDanceSteps_0_daze: {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0_daze',
    },
  },
  ChainAttackInterwovenDanceSteps_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0_anomBuildup',
    },
  },
  UltimateDazzlingCurtainCall_0_dmg: {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0_dmg',
    },
  },
  UltimateDazzlingCurtainCall_0_daze: {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0_daze',
    },
  },
  UltimateDazzlingCurtainCall_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0_anomBuildup',
    },
  },
  QuickAssistFeatherglowRebirth_0_dmg: {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0_dmg',
    },
  },
  QuickAssistFeatherglowRebirth_0_daze: {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0_daze',
    },
  },
  QuickAssistFeatherglowRebirth_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0_anomBuildup',
    },
  },
  DefensiveAssistFleetingLight_0_dmg: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0_dmg',
    },
  },
  DefensiveAssistFleetingLight_0_daze: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0_daze',
    },
  },
  DefensiveAssistFleetingLight_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0_anomBuildup',
    },
  },
  DefensiveAssistFleetingLight_1_dmg: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1_dmg',
    },
  },
  DefensiveAssistFleetingLight_1_daze: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1_daze',
    },
  },
  DefensiveAssistFleetingLight_1_anomBuildup: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1_anomBuildup',
    },
  },
  DefensiveAssistFleetingLight_2_dmg: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2_dmg',
    },
  },
  DefensiveAssistFleetingLight_2_daze: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2_daze',
    },
  },
  DefensiveAssistFleetingLight_2_anomBuildup: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2_anomBuildup',
    },
  },
  AssistFollowUpAwakeningGlimmer_0_dmg: {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0_dmg',
    },
  },
  AssistFollowUpAwakeningGlimmer_0_daze: {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0_daze',
    },
  },
  AssistFollowUpAwakeningGlimmer_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0_anomBuildup',
    },
  },
  AssistFlowerFeatherDance_0_dmg: {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0_dmg',
    },
  },
  AssistFlowerFeatherDance_0_daze: {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0_daze',
    },
  },
  AssistFlowerFeatherDance_0_anomBuildup: {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0_anomBuildup',
    },
  },
  luminizeRainbowsEndDmgInst: {
    sheet: 'Remielle',
    name: 'luminizeRainbowsEndDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'anomaly',
      damageType2: 'luminize',
      name: 'luminizeRainbowsEndDmgInst',
    },
  },
  luminizeFleetingGraceDmgInst: {
    sheet: 'Remielle',
    name: 'luminizeFleetingGraceDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'anomaly',
      damageType2: 'luminize',
      name: 'luminizeFleetingGraceDmgInst',
    },
  },
  luminizeUltimateDmgInst: {
    sheet: 'Remielle',
    name: 'luminizeUltimateDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'anomaly',
      damageType2: 'luminize',
      name: 'luminizeUltimateDmgInst',
    },
  },
  luminizeFlowerFeatherDmgInst: {
    sheet: 'Remielle',
    name: 'luminizeFlowerFeatherDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'anomaly',
      damageType2: 'luminize',
      name: 'luminizeFlowerFeatherDmgInst',
    },
  },
} as const
