// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Roxy',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Roxy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'anomaly',
      damageType2: 'windswept',
      name: 'anomalyDmgInst',
    },
  },
  abloomDmgInst: {
    sheet: 'Roxy',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Roxy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Roxy',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'dazeInst',
    },
  },
  BasicAttackDoStayAWhile_0_dmg: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0_dmg',
    },
  },
  BasicAttackDoStayAWhile_0_daze: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0_daze',
    },
  },
  BasicAttackDoStayAWhile_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0_anomBuildup',
    },
  },
  BasicAttackDoStayAWhile_1_dmg: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1_dmg',
    },
  },
  BasicAttackDoStayAWhile_1_daze: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1_daze',
    },
  },
  BasicAttackDoStayAWhile_1_anomBuildup: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1_anomBuildup',
    },
  },
  BasicAttackDoStayAWhile_2_dmg: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2_dmg',
    },
  },
  BasicAttackDoStayAWhile_2_daze: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2_daze',
    },
  },
  BasicAttackDoStayAWhile_2_anomBuildup: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2_anomBuildup',
    },
  },
  BasicAttackDoStayAWhile_3_dmg: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3_dmg',
    },
  },
  BasicAttackDoStayAWhile_3_daze: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3_daze',
    },
  },
  BasicAttackDoStayAWhile_3_anomBuildup: {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3_anomBuildup',
    },
  },
  DashAttackForgiveMyRudeness_0_dmg: {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0_dmg',
    },
  },
  DashAttackForgiveMyRudeness_0_daze: {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0_daze',
    },
  },
  DashAttackForgiveMyRudeness_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0_anomBuildup',
    },
  },
  DodgeCounterReturnedCourtesy_0_dmg: {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0_dmg',
    },
  },
  DodgeCounterReturnedCourtesy_0_daze: {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0_daze',
    },
  },
  DodgeCounterReturnedCourtesy_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0_anomBuildup',
    },
  },
  SpecialAttackForgiveMeForNotSeeingYouOff_0_dmg: {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_dmg',
    },
  },
  SpecialAttackForgiveMeForNotSeeingYouOff_0_daze: {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_daze',
    },
  },
  SpecialAttackForgiveMeForNotSeeingYouOff_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0_anomBuildup',
    },
  },
  SpecialAttackMuchObliged_0_dmg: {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0_dmg',
    },
  },
  SpecialAttackMuchObliged_0_daze: {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0_daze',
    },
  },
  SpecialAttackMuchObliged_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0_anomBuildup',
    },
  },
  EXSpecialAttackDontCatchAChill_0_dmg: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0_dmg',
    },
  },
  EXSpecialAttackDontCatchAChill_0_daze: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0_daze',
    },
  },
  EXSpecialAttackDontCatchAChill_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0_anomBuildup',
    },
  },
  EXSpecialAttackDontCatchAChill_1_dmg: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1_dmg',
    },
  },
  EXSpecialAttackDontCatchAChill_1_daze: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1_daze',
    },
  },
  EXSpecialAttackDontCatchAChill_1_anomBuildup: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1_anomBuildup',
    },
  },
  EXSpecialAttackKindlyRestInPeace_0_dmg: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0_dmg',
    },
  },
  EXSpecialAttackKindlyRestInPeace_0_daze: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0_daze',
    },
  },
  EXSpecialAttackKindlyRestInPeace_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0_anomBuildup',
    },
  },
  EXSpecialAttackKindlyRestInPeace_1_dmg: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1_dmg',
    },
  },
  EXSpecialAttackKindlyRestInPeace_1_daze: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1_daze',
    },
  },
  EXSpecialAttackKindlyRestInPeace_1_anomBuildup: {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1_anomBuildup',
    },
  },
  StormsEye_0_dmg: {
    sheet: 'Roxy',
    name: 'StormsEye_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_0_dmg',
    },
  },
  StormsEye_0_daze: {
    sheet: 'Roxy',
    name: 'StormsEye_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_0_daze',
    },
  },
  StormsEye_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'StormsEye_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_0_anomBuildup',
    },
  },
  StormsEye_1_dmg: {
    sheet: 'Roxy',
    name: 'StormsEye_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_1_dmg',
    },
  },
  StormsEye_1_daze: {
    sheet: 'Roxy',
    name: 'StormsEye_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_1_daze',
    },
  },
  StormsEye_1_anomBuildup: {
    sheet: 'Roxy',
    name: 'StormsEye_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_1_anomBuildup',
    },
  },
  StormsEye_2_dmg: {
    sheet: 'Roxy',
    name: 'StormsEye_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_2_dmg',
    },
  },
  StormsEye_2_daze: {
    sheet: 'Roxy',
    name: 'StormsEye_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_2_daze',
    },
  },
  StormsEye_2_anomBuildup: {
    sheet: 'Roxy',
    name: 'StormsEye_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'StormsEye_2_anomBuildup',
    },
  },
  ChainAttackGaleBurialGreatHammer_0_dmg: {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0_dmg',
    },
  },
  ChainAttackGaleBurialGreatHammer_0_daze: {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0_daze',
    },
  },
  ChainAttackGaleBurialGreatHammer_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0_anomBuildup',
    },
  },
  UltimateRequiemForTheNightBurial_0_dmg: {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0_dmg',
    },
  },
  UltimateRequiemForTheNightBurial_0_daze: {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0_daze',
    },
  },
  UltimateRequiemForTheNightBurial_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0_anomBuildup',
    },
  },
  AssistMoreOvertime_0_dmg: {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'AssistMoreOvertime_0_dmg',
    },
  },
  AssistMoreOvertime_0_daze: {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'AssistMoreOvertime_0_daze',
    },
  },
  AssistMoreOvertime_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'AssistMoreOvertime_0_anomBuildup',
    },
  },
  QuickAssistAtYourService_0_dmg: {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAtYourService_0_dmg',
    },
  },
  QuickAssistAtYourService_0_daze: {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAtYourService_0_daze',
    },
  },
  QuickAssistAtYourService_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAtYourService_0_anomBuildup',
    },
  },
  DefensiveAssistAllowMeToAssist_0_dmg: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0_dmg',
    },
  },
  DefensiveAssistAllowMeToAssist_0_daze: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0_daze',
    },
  },
  DefensiveAssistAllowMeToAssist_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0_anomBuildup',
    },
  },
  DefensiveAssistAllowMeToAssist_1_dmg: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1_dmg',
    },
  },
  DefensiveAssistAllowMeToAssist_1_daze: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1_daze',
    },
  },
  DefensiveAssistAllowMeToAssist_1_anomBuildup: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1_anomBuildup',
    },
  },
  DefensiveAssistAllowMeToAssist_2_dmg: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2_dmg',
    },
  },
  DefensiveAssistAllowMeToAssist_2_daze: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2_daze',
    },
  },
  DefensiveAssistAllowMeToAssist_2_anomBuildup: {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2_anomBuildup',
    },
  },
  AssistFollowUpMidnightCode_0_dmg: {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0_dmg',
    },
  },
  AssistFollowUpMidnightCode_0_daze: {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0_daze',
    },
  },
  AssistFollowUpMidnightCode_0_anomBuildup: {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0_anomBuildup',
    },
  },
} as const
