// WARNING: Generated file, do not modify
export const buffs = {
  ability_basic_dmg_: {
    sheet: 'StarlightBilly',
    name: 'ability_basic_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'basic',
      name: 'ability_basic_dmg_',
    },
    team: false,
  },
  ability_chain_dmg_: {
    sheet: 'StarlightBilly',
    name: 'ability_chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'chain',
      name: 'ability_chain_dmg_',
    },
    team: false,
  },
  ability_ult_dmg_: {
    sheet: 'StarlightBilly',
    name: 'ability_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'ult',
      name: 'ability_ult_dmg_',
    },
    team: false,
  },
  ability_exSpecial_dmg_: {
    sheet: 'StarlightBilly',
    name: 'ability_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'exSpecial',
      name: 'ability_exSpecial_dmg_',
    },
    team: false,
  },
  core_critDmg: {
    sheet: 'StarlightBilly',
    name: 'core_critDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'StarlightBilly',
      name: 'core_critDmg',
    },
    team: false,
  },
  core_hpSheerForce: {
    sheet: 'StarlightBilly',
    name: 'core_hpSheerForce',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'sheerForce',
      sheet: 'StarlightBilly',
      name: 'core_hpSheerForce',
    },
    team: false,
  },
  m1_physResIgn: {
    sheet: 'StarlightBilly',
    name: 'm1_physResIgn',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'm1_physResIgn',
    },
    team: false,
  },
  m4_critDmg: {
    sheet: 'StarlightBilly',
    name: 'm4_critDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'StarlightBilly',
      name: 'm4_critDmg',
    },
    team: false,
  },
  m2_basic_dmg_: {
    sheet: 'StarlightBilly',
    name: 'm2_basic_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'basic',
      name: 'm2_basic_dmg_',
    },
    team: false,
  },
  m2_ult_dmg_: {
    sheet: 'StarlightBilly',
    name: 'm2_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'ult',
      name: 'm2_ult_dmg_',
    },
    team: false,
  },
  m2_exSpecial_dmg_: {
    sheet: 'StarlightBilly',
    name: 'm2_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'exSpecial',
      name: 'm2_exSpecial_dmg_',
    },
    team: false,
  },
  m6_basic_sheer_: {
    sheet: 'StarlightBilly',
    name: 'm6_basic_sheer_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'basic',
      name: 'm6_basic_sheer_',
    },
    team: false,
  },
  m6_ult_sheer_: {
    sheet: 'StarlightBilly',
    name: 'm6_ult_sheer_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'StarlightBilly',
      damageType1: 'ult',
      name: 'm6_ult_sheer_',
    },
    team: false,
  },
} as const
