// WARNING: Generated file, do not modify
export const buffs = {
  exSpecial_sheerForce: {
    sheet: 'Lucia',
    name: 'exSpecial_sheerForce',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheerForce',
      sheet: 'Lucia',
      name: 'exSpecial_sheerForce',
    },
    team: true,
  },
  exSpecial_harmony_dmg_: {
    sheet: 'Lucia',
    name: 'exSpecial_harmony_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'Lucia',
      name: 'exSpecial_harmony_dmg_',
    },
    team: false,
  },
  core_hp_: {
    sheet: 'Lucia',
    name: 'core_hp_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'hp_',
      sheet: 'Lucia',
      name: 'core_hp_',
    },
    team: true,
  },
  core_common_dmg_: {
    sheet: 'Lucia',
    name: 'core_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Lucia',
      name: 'core_common_dmg_',
    },
    team: false,
  },
  ability_crit_dmg_: {
    sheet: 'Lucia',
    name: 'ability_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Lucia',
      name: 'ability_crit_dmg_',
    },
    team: true,
  },
  m1_resIgn_: {
    sheet: 'Lucia',
    name: 'm1_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Lucia',
      name: 'm1_resIgn_',
    },
    team: true,
  },
  m2_harmony_dmg_: {
    sheet: 'Lucia',
    name: 'm2_harmony_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Lucia',
      name: 'm2_harmony_dmg_',
    },
    team: false,
  },
  m2_sheer_dmg_: {
    sheet: 'Lucia',
    name: 'm2_sheer_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'Lucia',
      name: 'm2_sheer_dmg_',
    },
    team: true,
  },
  m6_atk_: {
    sheet: 'Lucia',
    name: 'm6_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Lucia',
      name: 'm6_atk_',
    },
    team: false,
  },
  m6_harmony_crit_: {
    sheet: 'Lucia',
    name: 'm6_harmony_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Lucia',
      name: 'm6_harmony_crit_',
    },
    team: false,
  },
  m6_harmony_crit_dmg_: {
    sheet: 'Lucia',
    name: 'm6_harmony_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Lucia',
      name: 'm6_harmony_crit_dmg_',
    },
    team: false,
  },
} as const
