// WARNING: Generated file, do not modify
export const buffs = {
  core_critPerCritDmg: {
    sheet: 'Claret',
    name: 'core_critPerCritDmg',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'crit_',
      sheet: 'Claret',
      name: 'core_critPerCritDmg',
    },
    team: false,
  },
  core_crimson_crit_: {
    sheet: 'Claret',
    name: 'core_crimson_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Claret',
      name: 'core_crimson_crit_',
    },
    team: false,
  },
  core_crimson_gashBuildup_: {
    sheet: 'Claret',
    name: 'core_crimson_gashBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'gashBuildup_',
      sheet: 'Claret',
      name: 'core_crimson_gashBuildup_',
    },
    team: false,
  },
  core_perfectDodge_dmg_: {
    sheet: 'Claret',
    name: 'core_perfectDodge_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Claret',
      name: 'core_perfectDodge_dmg_',
    },
    team: false,
  },
  ability_remnant_laceration_: {
    sheet: 'Claret',
    name: 'ability_remnant_laceration_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'laceration_dmg_',
      sheet: 'Claret',
      name: 'ability_remnant_laceration_',
    },
    team: false,
  },
  team_ability_remnant_laceration_: {
    sheet: 'Claret',
    name: 'team_ability_remnant_laceration_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'laceration_dmg_',
      sheet: 'Claret',
      name: 'team_ability_remnant_laceration_',
    },
    team: true,
  },
  m1_gashBuildup_: {
    sheet: 'Claret',
    name: 'm1_gashBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'gashBuildup_',
      sheet: 'Claret',
      name: 'm1_gashBuildup_',
    },
    team: false,
  },
  m1_maim_dmg_: {
    sheet: 'Claret',
    name: 'm1_maim_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sharp_dmg_',
      sheet: 'Claret',
      name: 'm1_maim_dmg_',
    },
    team: false,
  },
  m1_maim_mult_display_: {
    sheet: 'Claret',
    name: 'm1_maim_mult_display_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Claret',
      name: 'm1_maim_mult_display_',
    },
    team: false,
  },
  m2_electric_resIgn_: {
    sheet: 'Claret',
    name: 'm2_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Claret',
      attribute: 'electric',
      name: 'm2_electric_resIgn_',
    },
    team: false,
  },
  m4_starforging_dmg_: {
    sheet: 'Claret',
    name: 'm4_starforging_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Claret',
      name: 'm4_starforging_dmg_',
    },
    team: false,
  },
  m4_resonant_dmg_: {
    sheet: 'Claret',
    name: 'm4_resonant_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Claret',
      name: 'm4_resonant_dmg_',
    },
    team: false,
  },
  m4_trial_dmg_: {
    sheet: 'Claret',
    name: 'm4_trial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Claret',
      name: 'm4_trial_dmg_',
    },
    team: false,
  },
} as const
