// WARNING: Generated file, do not modify
export const formulas = {
  sharpDmgInst: {
    sheet: 'Claret',
    name: 'sharpDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'sharp',
      name: 'sharpDmgInst',
    },
  },
  gashBuildupInst: {
    sheet: 'Claret',
    name: 'gashBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'gash',
      name: 'gashBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Claret',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackBloodforgingFourForms_0_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0_dmg',
    },
  },
  BasicAttackBloodforgingFourForms_0_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0_daze',
    },
  },
  BasicAttackBloodforgingFourForms_0_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0_gashBuildup',
    },
  },
  BasicAttackBloodforgingFourForms_1_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1_dmg',
    },
  },
  BasicAttackBloodforgingFourForms_1_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1_daze',
    },
  },
  BasicAttackBloodforgingFourForms_1_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1_gashBuildup',
    },
  },
  BasicAttackBloodforgingFourForms_2_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2_dmg',
    },
  },
  BasicAttackBloodforgingFourForms_2_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2_daze',
    },
  },
  BasicAttackBloodforgingFourForms_2_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2_gashBuildup',
    },
  },
  BasicAttackBloodforgingFourForms_3_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3_dmg',
    },
  },
  BasicAttackBloodforgingFourForms_3_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3_daze',
    },
  },
  BasicAttackBloodforgingFourForms_3_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3_gashBuildup',
    },
  },
  BasicAttackBloodbloomOathStarforging_0_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0_dmg',
    },
  },
  BasicAttackBloodbloomOathStarforging_0_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0_daze',
    },
  },
  BasicAttackBloodbloomOathStarforging_0_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0_gashBuildup',
    },
  },
  BasicAttackBloodbloomOathStarforging_1_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1_dmg',
    },
  },
  BasicAttackBloodbloomOathStarforging_1_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1_daze',
    },
  },
  BasicAttackBloodbloomOathStarforging_1_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1_gashBuildup',
    },
  },
  BasicAttackBloodbloomOathStarforging_2_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2_dmg',
    },
  },
  BasicAttackBloodbloomOathStarforging_2_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2_daze',
    },
  },
  BasicAttackBloodbloomOathStarforging_2_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2_gashBuildup',
    },
  },
  BasicAttackBloodbloomOathStarforging_3_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3_dmg',
    },
  },
  BasicAttackBloodbloomOathStarforging_3_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3_daze',
    },
  },
  BasicAttackBloodbloomOathStarforging_3_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3_gashBuildup',
    },
  },
  BasicAttackBloodbloomOathSubduingAxe_0_dmg: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0_dmg',
    },
  },
  BasicAttackBloodbloomOathSubduingAxe_0_daze: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0_daze',
    },
  },
  BasicAttackBloodbloomOathSubduingAxe_0_gashBuildup: {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0_gashBuildup',
    },
  },
  DashAttackTempering_0_dmg: {
    sheet: 'Claret',
    name: 'DashAttackTempering_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTempering_0_dmg',
    },
  },
  DashAttackTempering_0_daze: {
    sheet: 'Claret',
    name: 'DashAttackTempering_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTempering_0_daze',
    },
  },
  DashAttackTempering_0_gashBuildup: {
    sheet: 'Claret',
    name: 'DashAttackTempering_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTempering_0_gashBuildup',
    },
  },
  DodgeCounterReturningEdge_0_dmg: {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0_dmg',
    },
  },
  DodgeCounterReturningEdge_0_daze: {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0_daze',
    },
  },
  DodgeCounterReturningEdge_0_gashBuildup: {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0_gashBuildup',
    },
  },
  DodgeCounterBloodbloomOathReturningEdge_0_dmg: {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0_dmg',
    },
  },
  DodgeCounterBloodbloomOathReturningEdge_0_daze: {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0_daze',
    },
  },
  DodgeCounterBloodbloomOathReturningEdge_0_gashBuildup: {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0_gashBuildup',
    },
  },
  SpecialAttackPorcelumesFirstCall_0_dmg: {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0_dmg',
    },
  },
  SpecialAttackPorcelumesFirstCall_0_daze: {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0_daze',
    },
  },
  SpecialAttackPorcelumesFirstCall_0_gashBuildup: {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0_gashBuildup',
    },
  },
  EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_dmg: {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_dmg',
    },
  },
  EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_daze: {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_daze',
    },
  },
  EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_gashBuildup: {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0_gashBuildup',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_0_dmg: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_dmg',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_0_daze: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_daze',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_0_gashBuildup: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0_gashBuildup',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_1_dmg: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_dmg',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_1_daze: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_daze',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_1_gashBuildup: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1_gashBuildup',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_2_dmg: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_dmg',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_2_daze: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_daze',
    },
  },
  SpecialAttackBloodbloomOathCleavingGoldAndIron_2_gashBuildup: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2_gashBuildup',
    },
  },
  SpecialAttackBloodbloomOathBloodBurialAssault_0_dmg: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_dmg',
    },
  },
  SpecialAttackBloodbloomOathBloodBurialAssault_0_daze: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_daze',
    },
  },
  SpecialAttackBloodbloomOathBloodBurialAssault_0_gashBuildup: {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0_gashBuildup',
    },
  },
  ChainAttackBloodbloomOathResonantBloodPact_0_dmg: {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0_dmg',
    },
  },
  ChainAttackBloodbloomOathResonantBloodPact_0_daze: {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0_daze',
    },
  },
  ChainAttackBloodbloomOathResonantBloodPact_0_gashBuildup: {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0_gashBuildup',
    },
  },
  UltimateBloodbloomOathTrialAfterTrial_0_dmg: {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0_dmg',
    },
  },
  UltimateBloodbloomOathTrialAfterTrial_0_daze: {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0_daze',
    },
  },
  UltimateBloodbloomOathTrialAfterTrial_0_gashBuildup: {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0_gashBuildup',
    },
  },
  QuickAssistReturnOfTheDireMoon_0_dmg: {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0_dmg',
    },
  },
  QuickAssistReturnOfTheDireMoon_0_daze: {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0_daze',
    },
  },
  QuickAssistReturnOfTheDireMoon_0_gashBuildup: {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0_gashBuildup',
    },
  },
  QuickAssistBloodbloomOathReturnOfTheDireMoon_0_dmg: {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_dmg',
    },
  },
  QuickAssistBloodbloomOathReturnOfTheDireMoon_0_daze: {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_daze',
    },
  },
  QuickAssistBloodbloomOathReturnOfTheDireMoon_0_gashBuildup: {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0_gashBuildup',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_0_dmg: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_dmg',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_0_daze: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_daze',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_0_gashBuildup: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0_gashBuildup',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_1_dmg: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_dmg',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_1_daze: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_daze',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_1_gashBuildup: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1_gashBuildup',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_2_dmg: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_dmg',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_2_daze: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_daze',
    },
  },
  DefensiveAssistUnyieldingHeartOfTheFurnace_2_gashBuildup: {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2_gashBuildup',
    },
  },
  AssistFollowUpBloodbloomOathPureforgedEdge_0_dmg: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_dmg',
    },
  },
  AssistFollowUpBloodbloomOathPureforgedEdge_0_daze: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_daze',
    },
  },
  AssistFollowUpBloodbloomOathPureforgedEdge_0_gashBuildup: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0_gashBuildup',
    },
  },
  CounterAssistGiveNotAnInchOfSteel_0_dmg: {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType1: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0_dmg',
    },
  },
  CounterAssistGiveNotAnInchOfSteel_0_daze: {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType1: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0_daze',
    },
  },
  CounterAssistGiveNotAnInchOfSteel_0_gashBuildup: {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType1: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0_gashBuildup',
    },
  },
  AssistFollowUpBloodbloomOathHammerIntoShape_0_dmg: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sharpDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_dmg',
    },
  },
  AssistFollowUpBloodbloomOathHammerIntoShape_0_daze: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_daze',
    },
  },
  AssistFollowUpBloodbloomOathHammerIntoShape_0_gashBuildup: {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_gashBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'gashBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0_gashBuildup',
    },
  },
  m6_maim: {
    sheet: 'Claret',
    name: 'm6_maim',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'maimDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      name: 'm6_maim',
    },
  },
} as const
