// WARNING: Generated file, do not modify
export const buffs = {
  common_dmg_: {
    sheet: 'AstraYao',
    name: 'common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'AstraYao',
      name: 'common_dmg_',
    },
    team: true,
  },
  crit_dmg_: {
    sheet: 'AstraYao',
    name: 'crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'AstraYao',
      name: 'crit_dmg_',
    },
    team: true,
  },
  core_atk: {
    sheet: 'AstraYao',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'AstraYao',
      name: 'core_atk',
    },
    team: true,
  },
  m1_resRed_: {
    sheet: 'AstraYao',
    name: 'm1_resRed_',
    tag: {
      et: 'display',
      qt: 'common',
      q: 'resRed_',
      sheet: 'AstraYao',
      name: 'm1_resRed_',
    },
    team: false,
  },
  m4_attack_quickAssist_extraDmg: {
    sheet: 'AstraYao',
    name: 'm4_attack_quickAssist_extraDmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'flat_dmg',
      sheet: 'AstraYao',
      specialty: 'attack',
      damageType1: 'quickAssist',
      name: 'm4_attack_quickAssist_extraDmg',
    },
    team: true,
  },
  m4_anomaly_quickAssist_anomBuildup_: {
    sheet: 'AstraYao',
    name: 'm4_anomaly_quickAssist_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'AstraYao',
      specialty: 'anomaly',
      damageType1: 'quickAssist',
      name: 'm4_anomaly_quickAssist_anomBuildup_',
    },
    team: true,
  },
  m4_stun_quickAssist_dazeInc_: {
    sheet: 'AstraYao',
    name: 'm4_stun_quickAssist_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'AstraYao',
      specialty: 'stun',
      damageType1: 'quickAssist',
      name: 'm4_stun_quickAssist_dazeInc_',
    },
    team: true,
  },
  m6_crit_: {
    sheet: 'AstraYao',
    name: 'm6_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'AstraYao',
      name: 'm6_crit_',
    },
    team: false,
  },
  m6_mv_mult_: {
    sheet: 'AstraYao',
    name: 'm6_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'mv_mult_',
      sheet: 'AstraYao',
      name: 'm6_mv_mult_',
    },
    team: false,
  },
  m6_capriccio_crit_: {
    sheet: 'AstraYao',
    name: 'm6_capriccio_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'AstraYao',
      name: 'm6_capriccio_crit_',
    },
    team: false,
  },
} as const
