// WARNING: Generated file, do not modify
export const buffs = {
  ult_ice_dmg_: {
    sheet: 'Miyabi',
    name: 'ult_ice_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'ult_ice_dmg_',
    },
    team: false,
  },
  core_frost_anomBuildup_: {
    sheet: 'Miyabi',
    name: 'core_frost_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'core_frost_anomBuildup_',
    },
    team: false,
  },
  core_anomBuildup_: {
    sheet: 'Miyabi',
    name: 'core_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Miyabi',
      name: 'core_anomBuildup_',
    },
    team: true,
  },
  ability_dmg_: {
    sheet: 'Miyabi',
    name: 'ability_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Miyabi',
      name: 'ability_dmg_',
    },
    team: false,
  },
  ability_ice_resIgn_: {
    sheet: 'Miyabi',
    name: 'ability_ice_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'ability_ice_resIgn_',
    },
    team: false,
  },
  m1_defIgn_: {
    sheet: 'Miyabi',
    name: 'm1_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Miyabi',
      name: 'm1_defIgn_',
    },
    team: false,
  },
  m1_anomBuildup_: {
    sheet: 'Miyabi',
    name: 'm1_anomBuildup_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildup_',
      sheet: 'Miyabi',
      name: 'm1_anomBuildup_',
    },
    team: true,
  },
  m2_dmg_: {
    sheet: 'Miyabi',
    name: 'm2_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Miyabi',
      name: 'm2_dmg_',
    },
    team: false,
  },
  m2_dodgeCounter_dmg_: {
    sheet: 'Miyabi',
    name: 'm2_dodgeCounter_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Miyabi',
      damageType1: 'dodgeCounter',
      name: 'm2_dodgeCounter_dmg_',
    },
    team: false,
  },
  m2_crit_: {
    sheet: 'Miyabi',
    name: 'm2_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Miyabi',
      name: 'm2_crit_',
    },
    team: false,
  },
  m4_frostburnBreak_dmg_: {
    sheet: 'Miyabi',
    name: 'm4_frostburnBreak_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Miyabi',
      name: 'm4_frostburnBreak_dmg_',
    },
    team: false,
  },
  m6_dmg_: {
    sheet: 'Miyabi',
    name: 'm6_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Miyabi',
      name: 'm6_dmg_',
    },
    team: false,
  },
} as const
