// WARNING: Generated file, do not modify
export const buffs = {
  core_patrol_crit_: {
    sheet: 'Sigrid',
    name: 'core_patrol_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Sigrid',
      name: 'core_patrol_crit_',
    },
    team: false,
  },
  ability_atk: {
    sheet: 'Sigrid',
    name: 'ability_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Sigrid',
      name: 'ability_atk',
    },
    team: false,
  },
  ability_contamination_dmg_: {
    sheet: 'Sigrid',
    name: 'ability_contamination_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Sigrid',
      name: 'ability_contamination_dmg_',
    },
    team: false,
  },
  m1_atk_: {
    sheet: 'Sigrid',
    name: 'm1_atk_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk_',
      sheet: 'Sigrid',
      name: 'm1_atk_',
    },
    team: false,
  },
  m1_overCap_dmg_: {
    sheet: 'Sigrid',
    name: 'm1_overCap_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'm1_overCap_dmg_',
    },
    team: false,
  },
  m2_frostTipped_pen_: {
    sheet: 'Sigrid',
    name: 'm2_frostTipped_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_frostTipped_pen_',
    },
    team: false,
  },
  m2_convergeSpear1_pen_: {
    sheet: 'Sigrid',
    name: 'm2_convergeSpear1_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_convergeSpear1_pen_',
    },
    team: false,
  },
  m2_convergeSpear2_pen_: {
    sheet: 'Sigrid',
    name: 'm2_convergeSpear2_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_convergeSpear2_pen_',
    },
    team: false,
  },
  m2_convergeSpear3_pen_: {
    sheet: 'Sigrid',
    name: 'm2_convergeSpear3_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_convergeSpear3_pen_',
    },
    team: false,
  },
  m2_dodgeCounter_pen_: {
    sheet: 'Sigrid',
    name: 'm2_dodgeCounter_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_dodgeCounter_pen_',
    },
    team: false,
  },
  m2_scatteredJade_pen_: {
    sheet: 'Sigrid',
    name: 'm2_scatteredJade_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_scatteredJade_pen_',
    },
    team: false,
  },
  m2_shatteredJade_pen_: {
    sheet: 'Sigrid',
    name: 'm2_shatteredJade_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_shatteredJade_pen_',
    },
    team: false,
  },
  m2_chain_pen_: {
    sheet: 'Sigrid',
    name: 'm2_chain_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_chain_pen_',
    },
    team: false,
  },
  m2_ult_pen_: {
    sheet: 'Sigrid',
    name: 'm2_ult_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_ult_pen_',
    },
    team: false,
  },
  m2_assistFollowUp_pen_: {
    sheet: 'Sigrid',
    name: 'm2_assistFollowUp_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Sigrid',
      name: 'm2_assistFollowUp_pen_',
    },
    team: false,
  },
  tempered_convergeSpear_dmg_: {
    sheet: 'Sigrid',
    name: 'tempered_convergeSpear_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Sigrid',
      name: 'tempered_convergeSpear_dmg_',
    },
    team: false,
  },
  m4_dmg_: {
    sheet: 'Sigrid',
    name: 'm4_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Sigrid',
      name: 'm4_dmg_',
    },
    team: false,
  },
  m6_convergeSpear1_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear1_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'm6_convergeSpear1_dmg_',
    },
    team: false,
  },
  m6_convergeSpear2_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear2_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'm6_convergeSpear2_dmg_',
    },
    team: false,
  },
  m6_convergeSpear3_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear3_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'm6_convergeSpear3_dmg_',
    },
    team: false,
  },
} as const
