// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Sigrid',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Sigrid',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Sigrid',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Sigrid',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Sigrid',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Sigrid',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackFrostTippedSpear_0_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_0_dmg',
    },
  },
  BasicAttackFrostTippedSpear_0_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_0_daze',
    },
  },
  BasicAttackFrostTippedSpear_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_0_anomBuildup',
    },
  },
  BasicAttackFrostTippedSpear_1_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_1_dmg',
    },
  },
  BasicAttackFrostTippedSpear_1_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_1_daze',
    },
  },
  BasicAttackFrostTippedSpear_1_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_1_anomBuildup',
    },
  },
  BasicAttackFrostTippedSpear_2_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_2_dmg',
    },
  },
  BasicAttackFrostTippedSpear_2_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_2_daze',
    },
  },
  BasicAttackFrostTippedSpear_2_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_2_anomBuildup',
    },
  },
  BasicAttackFrostTippedSpear_3_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_3_dmg',
    },
  },
  BasicAttackFrostTippedSpear_3_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_3_daze',
    },
  },
  BasicAttackFrostTippedSpear_3_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackFrostTippedSpear_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackFrostTippedSpear_3_anomBuildup',
    },
  },
  BasicAttackConvergingSpear1stStage_0_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear1stStage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear1stStage_0_dmg',
    },
  },
  BasicAttackConvergingSpear1stStage_0_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear1stStage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear1stStage_0_daze',
    },
  },
  BasicAttackConvergingSpear1stStage_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear1stStage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear1stStage_0_anomBuildup',
    },
  },
  BasicAttackConvergingSpear2ndStage_0_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear2ndStage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear2ndStage_0_dmg',
    },
  },
  BasicAttackConvergingSpear2ndStage_0_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear2ndStage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear2ndStage_0_daze',
    },
  },
  BasicAttackConvergingSpear2ndStage_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear2ndStage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear2ndStage_0_anomBuildup',
    },
  },
  BasicAttackConvergingSpear3rdStage_0_dmg: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear3rdStage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear3rdStage_0_dmg',
    },
  },
  BasicAttackConvergingSpear3rdStage_0_daze: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear3rdStage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear3rdStage_0_daze',
    },
  },
  BasicAttackConvergingSpear3rdStage_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'BasicAttackConvergingSpear3rdStage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackConvergingSpear3rdStage_0_anomBuildup',
    },
  },
  DashAttackWindchase_0_dmg: {
    sheet: 'Sigrid',
    name: 'DashAttackWindchase_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackWindchase_0_dmg',
    },
  },
  DashAttackWindchase_0_daze: {
    sheet: 'Sigrid',
    name: 'DashAttackWindchase_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackWindchase_0_daze',
    },
  },
  DashAttackWindchase_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'DashAttackWindchase_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackWindchase_0_anomBuildup',
    },
  },
  DodgeCounterCounterthrust_0_dmg: {
    sheet: 'Sigrid',
    name: 'DodgeCounterCounterthrust_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCounterthrust_0_dmg',
    },
  },
  DodgeCounterCounterthrust_0_daze: {
    sheet: 'Sigrid',
    name: 'DodgeCounterCounterthrust_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCounterthrust_0_daze',
    },
  },
  DodgeCounterCounterthrust_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'DodgeCounterCounterthrust_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCounterthrust_0_anomBuildup',
    },
  },
  SpecialAttackFrostflower_0_dmg: {
    sheet: 'Sigrid',
    name: 'SpecialAttackFrostflower_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFrostflower_0_dmg',
    },
  },
  SpecialAttackFrostflower_0_daze: {
    sheet: 'Sigrid',
    name: 'SpecialAttackFrostflower_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFrostflower_0_daze',
    },
  },
  SpecialAttackFrostflower_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'SpecialAttackFrostflower_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFrostflower_0_anomBuildup',
    },
  },
  EXSpecialAttackScatteredJade_0_dmg: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackScatteredJade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackScatteredJade_0_dmg',
    },
  },
  EXSpecialAttackScatteredJade_0_daze: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackScatteredJade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackScatteredJade_0_daze',
    },
  },
  EXSpecialAttackScatteredJade_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackScatteredJade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackScatteredJade_0_anomBuildup',
    },
  },
  EXSpecialAttackShatteredJade_0_dmg: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackShatteredJade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackShatteredJade_0_dmg',
    },
  },
  EXSpecialAttackShatteredJade_0_daze: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackShatteredJade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackShatteredJade_0_daze',
    },
  },
  EXSpecialAttackShatteredJade_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'EXSpecialAttackShatteredJade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackShatteredJade_0_anomBuildup',
    },
  },
  ChainAttackEncroachingIce_0_dmg: {
    sheet: 'Sigrid',
    name: 'ChainAttackEncroachingIce_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackEncroachingIce_0_dmg',
    },
  },
  ChainAttackEncroachingIce_0_daze: {
    sheet: 'Sigrid',
    name: 'ChainAttackEncroachingIce_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackEncroachingIce_0_daze',
    },
  },
  ChainAttackEncroachingIce_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'ChainAttackEncroachingIce_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackEncroachingIce_0_anomBuildup',
    },
  },
  UltimateFrozenHeavens_0_dmg: {
    sheet: 'Sigrid',
    name: 'UltimateFrozenHeavens_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateFrozenHeavens_0_dmg',
    },
  },
  UltimateFrozenHeavens_0_daze: {
    sheet: 'Sigrid',
    name: 'UltimateFrozenHeavens_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateFrozenHeavens_0_daze',
    },
  },
  UltimateFrozenHeavens_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'UltimateFrozenHeavens_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateFrozenHeavens_0_anomBuildup',
    },
  },
  QuickAssistIronSentinel_0_dmg: {
    sheet: 'Sigrid',
    name: 'QuickAssistIronSentinel_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIronSentinel_0_dmg',
    },
  },
  QuickAssistIronSentinel_0_daze: {
    sheet: 'Sigrid',
    name: 'QuickAssistIronSentinel_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIronSentinel_0_daze',
    },
  },
  QuickAssistIronSentinel_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'QuickAssistIronSentinel_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIronSentinel_0_anomBuildup',
    },
  },
  DefensiveAssistDauntlessCold_0_dmg: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_0_dmg',
    },
  },
  DefensiveAssistDauntlessCold_0_daze: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_0_daze',
    },
  },
  DefensiveAssistDauntlessCold_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_0_anomBuildup',
    },
  },
  DefensiveAssistDauntlessCold_1_dmg: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_1_dmg',
    },
  },
  DefensiveAssistDauntlessCold_1_daze: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_1_daze',
    },
  },
  DefensiveAssistDauntlessCold_1_anomBuildup: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_1_anomBuildup',
    },
  },
  DefensiveAssistDauntlessCold_2_dmg: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_2_dmg',
    },
  },
  DefensiveAssistDauntlessCold_2_daze: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_2_daze',
    },
  },
  DefensiveAssistDauntlessCold_2_anomBuildup: {
    sheet: 'Sigrid',
    name: 'DefensiveAssistDauntlessCold_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDauntlessCold_2_anomBuildup',
    },
  },
  AssistFollowUpDevouringFrost_0_dmg: {
    sheet: 'Sigrid',
    name: 'AssistFollowUpDevouringFrost_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDevouringFrost_0_dmg',
    },
  },
  AssistFollowUpDevouringFrost_0_daze: {
    sheet: 'Sigrid',
    name: 'AssistFollowUpDevouringFrost_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDevouringFrost_0_daze',
    },
  },
  AssistFollowUpDevouringFrost_0_anomBuildup: {
    sheet: 'Sigrid',
    name: 'AssistFollowUpDevouringFrost_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDevouringFrost_0_anomBuildup',
    },
  },
  m1_overCap_dmg_: {
    sheet: 'Sigrid',
    name: 'm1_overCap_dmg_',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'm1_overCap_dmg_',
    },
  },
  m6_convergeSpear1_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear1_dmg_',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'm6_convergeSpear1_dmg_',
    },
  },
  m6_convergeSpear2_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear2_dmg_',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'm6_convergeSpear2_dmg_',
    },
  },
  m6_convergeSpear3_dmg_: {
    sheet: 'Sigrid',
    name: 'm6_convergeSpear3_dmg_',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sigrid',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'm6_convergeSpear3_dmg_',
    },
  },
} as const
