// WARNING: Generated file, do not modify
export const buffs = {
  core_afterburn_dmg: {
    sheet: 'Burnice',
    name: 'core_afterburn_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Burnice',
      name: 'core_afterburn_dmg',
    },
    team: false,
  },
  potential_anomMas: {
    sheet: 'Burnice',
    name: 'potential_anomMas',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomMas',
      sheet: 'Burnice',
      name: 'potential_anomMas',
    },
    team: false,
  },
  potential_common_dmg_: {
    sheet: 'Burnice',
    name: 'potential_common_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Burnice',
      name: 'potential_common_dmg_',
    },
    team: false,
  },
  m2_pen_: {
    sheet: 'Burnice',
    name: 'm2_pen_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'pen_',
      sheet: 'Burnice',
      name: 'm2_pen_',
    },
    team: true,
  },
  m4_exSpecial_crit_: {
    sheet: 'Burnice',
    name: 'm4_exSpecial_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Burnice',
      damageType1: 'exSpecial',
      name: 'm4_exSpecial_crit_',
    },
    team: false,
  },
  m4_assistSkill_crit_: {
    sheet: 'Burnice',
    name: 'm4_assistSkill_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Burnice',
      skillType2: 'assistSkill',
      name: 'm4_assistSkill_crit_',
    },
    team: false,
  },
  m6_burn_fire_resIgn_: {
    sheet: 'Burnice',
    name: 'm6_burn_fire_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'm6_burn_fire_resIgn_',
    },
    team: false,
  },
  m6_fire_resIgn_: {
    sheet: 'Burnice',
    name: 'm6_fire_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Burnice',
      attribute: 'fire',
      name: 'm6_fire_resIgn_',
    },
    team: false,
  },
  m6_burn_dmg: {
    sheet: 'Burnice',
    name: 'm6_burn_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_mv_mult_',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'burn',
      name: 'm6_burn_dmg',
    },
    team: false,
  },
  m6_additional_afterburn_dmg: {
    sheet: 'Burnice',
    name: 'm6_additional_afterburn_dmg',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Burnice',
      name: 'm6_additional_afterburn_dmg',
    },
    team: false,
  },
} as const
