// WARNING: Generated file, do not modify
export const buffs = {
  ability_squad_crit_dmg_: {
    sheet: 'Cissia',
    name: 'ability_squad_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Cissia',
      name: 'ability_squad_crit_dmg_',
    },
    team: false,
  },
  ability_self_crit_dmg_: {
    sheet: 'Cissia',
    name: 'ability_self_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Cissia',
      name: 'ability_self_crit_dmg_',
    },
    team: false,
  },
  core_defIgn_: {
    sheet: 'Cissia',
    name: 'core_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'core_defIgn_',
    },
    team: true,
  },
  core_corrodeBone_dmg_: {
    sheet: 'Cissia',
    name: 'core_corrodeBone_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'core_corrodeBone_dmg_',
    },
    team: false,
  },
  core_corrodeBone_daze_: {
    sheet: 'Cissia',
    name: 'core_corrodeBone_daze_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'core_corrodeBone_daze_',
    },
    team: false,
  },
  m1_corrodeBone_resIgn_: {
    sheet: 'Cissia',
    name: 'm1_corrodeBone_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'm1_corrodeBone_resIgn_',
    },
    team: false,
  },
  core_corrodeBone_crit_: {
    sheet: 'Cissia',
    name: 'core_corrodeBone_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Cissia',
      name: 'core_corrodeBone_crit_',
    },
    team: true,
  },
  core_etherVeil_crit_dmg_: {
    sheet: 'Cissia',
    name: 'core_etherVeil_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Cissia',
      name: 'core_etherVeil_crit_dmg_',
    },
    team: true,
  },
  m1_electric_resIgn_: {
    sheet: 'Cissia',
    name: 'm1_electric_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'm1_electric_resIgn_',
    },
    team: true,
  },
  m2_serpentsKiss_dmg_: {
    sheet: 'Cissia',
    name: 'm2_serpentsKiss_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'm2_serpentsKiss_dmg_',
    },
    team: false,
  },
} as const
