name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint
        run: npx nx run-many --target=eslint:lint --fix=false --max-warnings=0

      - name: Typecheck
        run: npx nx run-many --target=typecheck

      - name: Test
        run: npx nx run-many --target=test

      - name: Build
        run: npx nx build zzz-frontend

      - name: Check Gen File
        run: |
          npx nx run-many -t gen-file
          test -z "$(git status --porcelain | tee /dev/stderr)"

      - name: Format
        run: yarn biome ci